### ISSUE TITLE
Change runtime code to deal with multiple runtime in runtime.json

### ISSUE THREAD

**Issue by ImperatorS79** [PhoenicisOrg/scripts#1005]
It will not work as expected currently.

**Comment by plata** [comment]
How do we handle multiple runtimes? Is it even useful to have this?

**Comment by ImperatorS79** [comment]
Ask @qparis, I am preparing a fix for phoenicis to always download the latest version.

**Comment by plata** [comment]
Ok so @qparis is it useful? Who should decide which runtime is required? I'm not really positive that this is feasible.

**Comment by qparis** [comment]
So far, and this will be the default behavior, all wine version will be assigned to the latest runtime. One day, we will need to fix a given runtime for a given wineversion

**Comment by plata** [comment]
Understood. I thought it was about multiple runtime versions for the same Wine version.
