### ISSUE TITLE
AdobeAir uses old checksum

### ISSUE THREAD

**Issue by madoar** [PhoenicisOrg/scripts#1012]
When installing the AdobeAir plugin I get the following message about a wrong checksum:

![grafik](https://user-images.githubusercontent.com/18488086/59562557-575b3000-902e-11e9-867b-bafb42c98783.png)

**Comment by ImperatorS79** [comment]
This will happen each time adobeair is updated, so it might be interesting to remove the checksum.

**Comment by Kreyren** [comment]
@ImperatorS79 **DO NOT REMOVE CHECKSUM!!!** very insane assuming adobe's security issues. 

- https://www.bbc.co.uk/news/technology-24740873

- https://www.zdnet.com/article/adobe-security-updates-released-for-critical-flash-acrobat-reader-bugs/

- https://forums.adobe.com/thread/2417261

- https://helpx.adobe.com/x-productkb/policy-pricing/customer-alert.html

**Comment by qparis** [comment]
+1 for removing the checksum

**Comment by Kreyren** [comment]
My checksum! My! my! my!

**Comment by qparis** [comment]
The adobe security holes are totally unrelated to the checksum issue. The checksum only helps to ensure that the file has not been altered during download and that’s all.
I suggest we remove it

**Comment by madoar** [comment]
I agree with @qparis. A checksum is can be mainly used to prevent two issues:
- the usage of a totally different (wrong) file
- transmission errors during file downloads

Errors located inside the successfully downloaded file (i.e no transmission errors occurred) don't belong in any of these categories.

I would even suggest to remove **all** Checksums from the verbs to prevent similar issues. Broken verbs are really bad for us because we often can't detect this in an automated way. This means that mainly end-users stumble over these issues which is really worrying.

**Comment by Kreyren** [comment]
> The adobe security holes are totally unrelated to the checksum issue.

Strongly disagree assuming that hijacking of adobe download server is likely scenario -> Checksum is the only thing that  i know of to protect users from this unless you want to ship phoenicis with clamav.

Seriously give me one good reason to remove checksum from anything.. :man_facepalming: 

>  The checksum only helps to ensure that the file has not been altered during download and that’s all.

### WRONG! 

It makes sure that the expected file has been downloaded. Making sure that the download was sucessful is just one usecase..

> I would even suggest to remove all Checksums from the verbs to prevent similar issues.

WHY ARE YOU SO INSAAANE, rather update the checksum or **IDEALLY** make a function which updates the checksum automatically based on results from virustotal.

> Broken verbs are really bad for us because we often can't detect this in an automated way. This means that mainly end-users stumble over these issues which is really worrying.

https://github.com/PhoenicisOrg/scripts/pull/908 Boom! two second fix that is easy to diagnose and make MR for. :man_facepalming: 

---

I even remember trusted repository with checksums from which we could fetch these, but i would have to find it..

---

Removing checksums are just a terrible hotfix, please dont do that

**Comment by apheliar** [comment]
you're idiots for trying to remove checksum

**Comment by Kreyren** [comment]
@apheliar thanks!

**Comment by qparis** [comment]
<img width="336" alt="Capture d’écran 2019-07-05 à 15 21 37" src="https://user-images.githubusercontent.com/373645/60725170-ab27ad80-9f38-11e9-9b4e-4d0a7544a663.png">

How could one have joined Github just to create one comment on a closed ticket. 

@Kreyren you have been warned several time. You are no longer welcomed on this community. 
When many different experts tell you the same thing, consider the chance that you might be on the wrong track.
