### ISSUE TITLE
Apply Formatting to "script.js" Files

### ISSUE THREAD

**Issue by madoar** [PhoenicisOrg/scripts#1027]
Currently we only apply formatting to our `*.json` files. 
I think it would be specify a required formatting for the `script.js` files, similar to what we do for the `.json` files at https://phoenicisorg.github.io/scripts/General/tools/.

I'm currently using 

```
npm install -g prettier
prettier --print-width 120 --use-tabs --write **/script.js
```

for the installer scripts in #1011. Maybe we could use `prettier` for the formatting and tweak the parameters a bit more.

@ImperatorS79 @plata @qparis what do you think?

**Comment by plata** [comment]
ESLint should already do that.

**Comment by madoar** [comment]
Yes but only on Travis right? I'm basically suggesting a client side solution which the developers can use to format their code. ESlint is not really a formatter but a linter, which helps you analyze the source code.

**Comment by plata** [comment]
No. You can use `--fix` (see [tools docs](https://phoenicisorg.github.io/scripts/General/tools/#eslint)).

**Comment by plata** [comment]
Can we close this?
