### ISSUE TITLE
"Download runtime json..." displayed as default message while installing a script

### ISSUE THREAD

**Issue by ImperatorS79** [PhoenicisOrg/scripts#1055]
See #959 at the end.

**Comment by plata** [comment]
The installation enters `_installRuntime` several times. Is this intended?

**Comment by ImperatorS79** [comment]
It should only do that when installing a wine package in `install`. I expected it was only called once.

**Comment by plata** [comment]
You can add a print out. It's called several times (of course the runtime is downloaded only once).

**Comment by plata** [comment]
This is a way more general issue: We want to control the wait message during `wine.run`. However, `wine.run` itself changes the wait message if e.g. Wine or the runtime is installed and cannot recover the initial wait message.
@qparis do you think it would make sense to have something like `wizar.currentWaitMessage`?

**Comment by qparis** [comment]
I would rather implement the wait message feature on the wine object imho

**Comment by madoar** [comment]
Just as a reminder: I'm planning to merge wine object and wine implementation over the next few days.

**Comment by plata** [comment]
@qparis can you elaborate?

**Comment by Zemogiter** [comment]
I confirm this still being the issue using the latest script repo and POL5 commit https://github.com/PhoenicisOrg/phoenicis/commit/f69f24f5d785d52e4b64bbae35ea4cf4993d2809

**Comment by plata** [comment]
I'm still not really sure how the solution proposed by @qparis could look like. Nevertheless, I don't think it makes sense to check the runtime json multiple times during one installation. Therefore I would propose to add a new member `_fetchedRuntimeJson` to `WineEngine` which is set to `true` the first time the json is downloaded. If it is `true`, do not download it again in https://github.com/PhoenicisOrg/scripts/blob/773a6dd909fe9869a7412d9765676b32613d18fd/Engines/Wine/Engine/Implementation/script.js#L149.

**Comment by ImperatorS79** [comment]
I do not even understand why the method is called multiple times. You do not need a new method. Just move `_installRuntime ` to a location where it is executed only once. And I do not see how it will solve the "bug" mentionned in the title..

**Comment by plata** [comment]
The problem is: where is that location?

**Comment by ImperatorS79** [comment]
@plata Here: https://github.com/PhoenicisOrg/scripts/blob/master/Engines/Wine/Engine/Implementation/script.js, It is called once line 360 and once line 407. The second one seems superfluous since we return if we cannot execute the first one.

**Comment by plata** [comment]
I don't think that's correct. If the second one is removed, you will not be able to change the Wine version for an existing prefix (iirc).

**Comment by ImperatorS79** [comment]
If you look closely, if the first one is not called, the second one is not either (there is a `return `in the `else`).

The change of wine version in an existing prefix is done in the `changeVersion `method.

**Comment by plata** [comment]
You're right. Nevertheless, I don't think it will solve the problem because the wizard message is set before `run` is called and even if `install()` is executed only once, it still calls `_installRuntime` which will change the wizard message.

**Comment by ImperatorS79** [comment]
Yes, it just solves the double call. How to set the wait message again ?

**Comment by plata** [comment]
Let's continue this part of the discussion in the PR.
