### ISSUE TITLE
adobeair: Fails to install on new checksum

### ISSUE THREAD

**Issue by Kreyren** [PhoenicisOrg/scripts#1061]
Fails to install with correct checksum https://gist.githubusercontent.com/Kreyren/5bd8d29fe4e3f93cc2e60d43420fa6c7/raw/188601982702a621e7b6602947578c6e7cbe737e/gdsgsdag

Relevant: https://bugs.winehq.org/show_bug.cgi?id=43506
Relevant: https://github.com/Winetricks/winetricks/issues/821

Installed on phoenicis-wine using winetricks which results in fatal: https://gist.githubusercontent.com/Kreyren/e265b0bd3e35776a643af464a41c0b9a/raw/c66f044278fe877d9f6ec87d0b7acdd256072bd4/dsgasdgasdg

Works no issue on winehq-staging wine on debian (wine-4.11 (Staging)
): https://gist.githubusercontent.com/Kreyren/515e20efa6b86032883e797fd7d88d2a/raw/0d3dd6f40cb5ce306a49fc863e107695673972ef/gfdgsfdgsfd

Conclusion: Blame @qparis phoenicis-wine blocker

**Comment by madoar** [comment]
Can you check if this is only the case with `wine-4.11` or if this also occurs with older versions?

**Comment by Kreyren** [comment]
> Can you check if this is only the case with `wine-4.11` or if this also occurs with older versions?

Checked just provided. Testing on demand.
