### ISSUE TITLE
REQUEST: Test using local wine

### ISSUE THREAD

**Issue by Kreyren** [PhoenicisOrg/scripts#1062]
Requestion option which allows using local-wine for testing alike:
![image](https://user-images.githubusercontent.com/11302521/60682804-01dbab80-9e95-11e9-887a-f539e1e40522.png)

Reasoning: Phoenicis-wine issues are very common and i would like to finish working on MRs that i can verify working locally without executing long script for preloads and executables. 

References:
- https://github.com/PhoenicisOrg/scripts/issues/1061
- https://github.com/PhoenicisOrg/scripts/pull/908
- https://github.com/PhoenicisOrg/scripts/pull/797
- https://github.com/PhoenicisOrg/scripts/pull/965
- https://github.com/PhoenicisOrg/scripts/pull/967
...

**Comment by plata** [comment]
Declined. This doesn't prove that the script works as expected.

**Comment by madoar** [comment]
I also don't see a pressing need for us to provide support for local wine installations. If you want support for local wine installations feel free to provide a PR.

**Comment by Kreyren** [comment]
> Declined. This doesn't prove that the script works as expected.

Wine is same anywhere and i can blame qparis with results since that would indicate phoenicis issue unless wineapp depends on specific system libs that are hard to sandbox.
