### ISSUE TITLE
Wine Implementation: "distribution" is not defined

### ISSUE THREAD

**Issue by madoar** [PhoenicisOrg/scripts#1078]
When looking at the issues found by `eslint` I discovered that the variable `distributed` in the line:
 
https://github.com/PhoenicisOrg/scripts/blob/ecd735e3b8530c70e95db10975cc8e8577897109/Engines/Wine/Engine/Implementation/script.js#L394

is not defined, i.e. the condition will always evaluate to false. I guess this is a bug.

**Comment by ImperatorS79** [comment]
Yep it is. There was a `distribution` var before that, but it was inside a `if` and I did not notice it ^^.

**Comment by plata** [comment]
@ImperatorS79 can you fix the issue?

**Comment by ImperatorS79** [comment]
Fixed by #1079.
