### ISSUE TITLE
Engine plugins as module?

### ISSUE THREAD

**Issue by plata** [PhoenicisOrg/scripts#1080]
Currently, the engine plugins extend the engine object module. As a result, they are e.g. included a bit differently compared to everything else. We could implement the plugins as normal modules and pass the engine as parameter.

**Comment by madoar** [comment]
Can you give an example how this would change the include syntax?

**Comment by plata** [comment]
now:
```Javascript
include("engines.wine.plugins.regedit");
```
then:
```Javascript
const Regedit = include("engines.wine.plugins.regedit");
```

**Comment by madoar** [comment]
And how do we use this plugin then? As far as I understand it, it would be moved to a new class and therefore not be part of the `Wine class` anymore right?

**Comment by plata** [comment]
Yes. So instead of
```Javascript
wine.regedit();
```
you would write
```Javascript
const regedit = new Regedit(wine);
regedit.run();
```

**Comment by madoar** [comment]
Alternatively we could also support a `static` method with the following syntax:

```javascript
Regedit.run(wine);
```

The problem with a static method is that we can't declare it in an interface.

How would you change the `Verb` and `Plugin` interfaces?

**Comment by plata** [comment]
Do we have to change the interfaces?

**Comment by madoar** [comment]
We do not have to but it gives a certain safety to script developers because every verb can be handled the same way. In addition we are then able to access the verbs from Java in a more elegant way.

**Comment by plata** [comment]
I cannot follow you right now.

**Comment by madoar** [comment]
If we define that **every** verb needs to provide a method with the following signature:

```java
/**
 * Installs the verb using the given engine
 */
void run(Engine engine);
```

This gives the script developers that use the verbs the safety that every verb can be called the same way, i.e. by calling `verb.run(wine)`. This is not the case if we don't add the method to the interface. In this case verb `A` could be called with `A.install(wine)`, while verb `B` could be called with `B.run(wine)` etc.

About the second point:
Currently we install the verbs by an additional class that only functions as a connection layer between JS and Java (Phoenicis). I think we may be able to remove this additional class and replace it by a generic one, that can be used from both inside the scripts and from inside Phoenicis.

**Comment by plata** [comment]
Now I understand. Yes, that would be nice.

**Comment by madoar** [comment]
Alternatively we could also think about supporting the following syntax:

```javascript
const Regedit = include("engines.wine.plugins.regedit");
...
wine.install(Regedit);
```

**Comment by plata** [comment]
Looks strange to me. You do not install regedit but you use it do edit the registry.

**Comment by madoar** [comment]
We don't need to call the method `install`, how about one of the following:

```javascript
wine.run(Regedit);
wine.execute(Regedit);
wine.process(Regedit);
wine.activate(Regedit);
```

The benefit of this approach is that we would still call a method of the `Wine` object and not one of the verb/plugin/setting object.

**Comment by plata** [comment]
> The benefit of this approach is that we would still call a method of the Wine object and not one of the verb/plugin/setting object.

For me, this is not a benefit. I would rather say the exact opposite: If plugins behave exactly like any other module, it is much easier to understand how they work.

**Comment by madoar** [comment]
Ok, I understand. Let's get a bit more concrete how these "engine plugins" could look like. Let's start with the verbs. 

For the verbs we could change our verb interface to the following (pseudocode):

```javascript
class Verb {
   /**
    * Convenience method to allow the following style:
    * Atmlib.with(engine).set(...).go();
    */
   static Verb with(Engine engine);

   /**
    * This method is optional. It is only provided for verbs that don't require any other parameters except the engine
    */
   static void withExecute(Engine engine);

   constructor(Engine engine);

   /**
    * Executes the verb
    */
   go();
}
```

For the `atmlib` verb the script could then look like the following:

```javascript
class Atmlib {
   static with(wine) {
      return new Atmlib(wine);
   }

   static withExecute(wine) {
      Atmlib.with(wine).go();
   }

   constructor(wine) {
      this.wine = wine;
   }

   go() {
      const setupFile = new Resource()
         .wizard(wine.wizard())
         .url("https://ftp.gnome.org/mirror/archive/ftp.sunet.se/pub/security/vendor/microsoft/win2000/Service_Packs/usa/W2KSP4_EN.EXE")
         .checksum("fadea6d94a014b039839fecc6e6a11c20afa4fa8")
         .name("W2ksp4_EN.exe")
         .get();

      new CabExtract()
         .archive(setupFile)
         .wizard(wine.wizard())
         .to(wine.system32directory())
         .extract();

      new CabExtract()
         .archive(wine.system32directory() + "/i386/atmlib.dl_")
         .wizard(wine.wizard())
         .to(wine.system32directory())
         .extract();

      remove(wine.system32directory() + "/i386/");
   }
}

// I think we need to do the "module.x" assignment after the class declaration to have the keyword "Atmlib" visible from inside the declared class
module.default = Atmlib;
```

An open question would then be how we provide the `install(container)` method that is required to install a verb from inside the UI. A possible solution would be to add it as an additional static method, i.e.:

```javascript
class Verb {
   ...
   static void install(String container);
}
```

What do you think?

**Comment by qparis** [comment]
I would avoid static methods.

**Comment by madoar** [comment]
We could also go only with the constructor but I think that kind of breaks the programming flow.
I like it more to write:

```javascript
Atmlib.with(wine)
   .set(x, a)
   .set(y, b)
   .go();
```

instead of:

```javascript
new Atmlib(wine)
   .set(x, a)
   .set(y, b)
   .go();
```

 or are you meaning something different?

**Comment by qparis** [comment]
The problem with the first syntax is that it could lead to race condition. Suppose two threads use the static builder in the same time, things could be messed up. Also, it is harder to test. 

This is why I always suggest using instances

**Comment by madoar** [comment]
Why does this lead to a race condition? Each call to the static method returns a new builder instance. Therefore the two callers won't access the same instance.

**Comment by qparis** [comment]
Amtlib.with() returns a new instance, right? If so, I guess we are fine

**Comment by plata** [comment]
I thought we cannot use `static` in Javascript anyways? Apart from that, we need to keep in mind that certain verbs/plugins need more parameters than just `wine` (e.g. the version).

**Comment by madoar** [comment]
> `Amtlib.with()` returns a new instance, right? If so, I guess we are fine

Exactly, `Amtlib.with(wine)` always returns a new instance. The idea behind the method is to hide the explicit `new` call because it kind of breaks the reading flow in my opinion.

> I thought we cannot use static in Javascript anyways?

It is not that we cannot use `static` in JavaScript. The issue with `static` in JS is that we are kind of limited in its usage. We can only use it define static methods. Therefore we are unable to define static fields and accessor methods.

What is interesting about `static` in JS is its implementation. I've read somewhere that `static` members of a class are properties of the constructor method. This should allow us to do the following:

Script `A`
```javascript
module.default = class {
   static install(container) {
      ...
   }
}
```

In Java:
```java
interface StaticClass {
   void install(String container);
}

Value included = (Value) phoenicisScriptEngine.evalAndReturn("include("A");", errorCallback);

StaticClass staticClass = included.as(StaticClass.class);
staticClass.install(container);
```

But I haven't tested this yet.

> Apart from that, we need to keep in mind that certain verbs/plugins need more parameters than just wine (e.g. the version).

This is not a problem, because the returned object by `static with(engine)` should be implemented using the builder pattern. This means that you can add as many other parameters as you want by adding corresponding methods to the returned object of `static with(engine)`.

**Comment by plata** [comment]
I think I would prefer to use the `new` instead of the `static` approach. It is closer to everything else, e.g. the way you create an engine, Downloader, Shortcut etc. As an example, see https://github.com/PhoenicisOrg/scripts/blob/920c415c38cfffca58d3813108893d1c50c69f44/Engines/Wine/QuickScript/Steam%20Script/script.js#L109

**Comment by madoar** [comment]
I'm fine either way, so you prefer:

```javascript
class Verb {
   /**
    * Installs the verb in the given container.
    * For this a new engine and verb instance is created 
    */
   static void install(String container);

   /**
    * Constructor
    */
   constructor(Engine engine);

   /**
    * Executes the verb
    */
   go();
}
```

?

Additional methods can be added by the concrete verb implementations like `Atmlib` as necessary. These methods are invisible to the Java Interface and need to be called by `static void install(String container)` internally.

**Comment by plata** [comment]
Why should the container be treated differently? 

Can't we:
```Javascript
new Verb()
    .withWine(wine)
    .withContainer("myContainer") // optional
    .go();
```
?

**Comment by madoar** [comment]
Because the verb can't be used without the engine. If you add the engine via a `withEngine` method you will need to do an additional validation in the `go` method that checks whether the engine is `null`/`undefined`. This is not required if you add it via the constructor, because you can then do the check directly in the constructor.

**Comment by plata** [comment]
So:

```Javascript
new Verb(wine)
    .withContainer("myContainer") // optional
    .withVersion("1.2.3") // optional
    .withSomeParameter(foo)
    .go();
```
?

**Comment by madoar** [comment]
Exactly!

**Comment by plata** [comment]
I think that should work. @ImperatorS79 @qparis any remarks?

**Comment by plata** [comment]
Can we close this?
