### ISSUE TITLE
Undefined "filesToExtract" in Xact Script

### ISSUE THREAD

**Issue by madoar** [PhoenicisOrg/scripts#1082]
I'm currently refactoring parts of the verbs and discovered a possible error in the `xact`script.

In the following line I believe `filesToExtract` to be unset/undefined:

https://github.com/PhoenicisOrg/scripts/blob/79537f88aecf4bbeb867fe0d22c5580bded786b9/Engines/Wine/Verbs/xact/script.js#L38

@plata @ImperatorS79 what do you think?

**Comment by ImperatorS79** [comment]
The script is normally working even with this error (because when I tested the script when I added this verb it was working). Feel free to update it so that the GUI part works.

**Comment by madoar** [comment]
I think that the line may be a copy&paste error and it should be:

```javascript
progressBar.setProgressPercentage(numberOfExtractedFiles * 100 / dllToRegsvr.length);
```

What do you think?

**Comment by ImperatorS79** [comment]
It seems so.
