### ISSUE TITLE
Unused "targetDirectory" function?

### ISSUE THREAD

**Issue by madoar** [PhoenicisOrg/scripts#1084]
I just stumbled across the `targetDirectory` function defined in:

https://github.com/PhoenicisOrg/scripts/blob/79537f88aecf4bbeb867fe0d22c5580bded786b9/Engines/Wine/Verbs/Windows%20XP%20SP%203/script.js#L16-L19

I can't find a place where it is used.
Additionally I think it is bad design to add it from **inside** a verb to the `Wine` instance.
I believe we can remove this method, but I would first like to hear your opinion @plata @ImperatorS79 about this. Is the method required? Is the method used at all currently? Do you think we can/should remove it?

**Comment by plata** [comment]
I think it can be removed. @qparis is that correct? I believe you wrote this verb.

**Comment by madoar** [comment]
Fixed in #1085
