### ISSUE TITLE
Missing "wizard" in "corefonts" Verb

### ISSUE THREAD

**Issue by madoar** [PhoenicisOrg/scripts#1092]
During the extraction of the font resources the wizard is not passed to `CabExtract` in:

https://github.com/PhoenicisOrg/scripts/blob/79537f88aecf4bbeb867fe0d22c5580bded786b9/Engines/Wine/Verbs/corefonts/script.js#L98-L102

**Comment by plata** [comment]
How could this work?

**Comment by madoar** [comment]
You mean how was it working before?
I have no clue... I guess the wizard was/is somehow optional...
