### ISSUE TITLE
Restructure "Windows version" Plugin Script

### ISSUE THREAD

**Issue by madoar** [PhoenicisOrg/scripts#1094]
Currently the `Windows version` verb returns a very sketchy and blurry defined `SetOsForApplication` object to the caller of `Wine.prototype.setOsForApplication`.

The issue with the return type of the method is that we normally return the `Wine` instance and not another object when calling a verb. Can we change this to something a bit more intuitive? Maybe the approaches in #1080 would be applicable here too?

**Comment by plata** [comment]
Yes, I think #1080 would solve this kind of issues for the plugins (also e.g. the "managed" plugin etc.).

**Comment by plata** [comment]
Is this done?
