### ISSUE TITLE
Wrong Archive File in Atmlib?

### ISSUE THREAD

**Issue by madoar** [PhoenicisOrg/scripts#1111]
During the Refactoring of the Verbs I've stumbled over the following line in the `atmlib` script:

https://github.com/PhoenicisOrg/scripts/blob/773a6dd909fe9869a7412d9765676b32613d18fd/Engines/Wine/Verbs/atmlib/script.js#L26

Should it be `atmlib.dl_` or something else like `atmlib.dll`?

**Comment by ImperatorS79** [comment]
You extract `atmlib.dll` from `atmlib.dl_` I assume. I have seen such things in another verb I coded.

**Comment by ImperatorS79** [comment]
This is the correct behaviour.
