### ISSUE TITLE
Steam no longer support windows xp after the library update

### ISSUE THREAD

**Issue by Zemogiter** [PhoenicisOrg/scripts#1138]
When Steam is done downloading updates and `SteamScript` tries to start Steram.exe for the first time you get the message that says Steam no longer supports your os. This is a problem because now we can no longer use the worarrounds to make steam browser work. I've tried it on Lutris since it applies none of the workarrounds we are using and the Library tab now works like steam browser (store, community etc.). Which is to say it dosen't work at all. 
This situation makes every steam script broken until we figure out a solution. Applies to both new `SteamScript` installations and existing prefixes.

**Comment by plata** [comment]
I have no idea how we could solve this. What I do not understand: Steam apps are installed/started via Steam api. This should work even without the library.

**Comment by Zemogiter** [comment]
We just need to make the library tab work because now it's either black or blinking.

**Comment by plata** [comment]
What will happen if we do not set it to winxp? If Steam does not run with winxp anymore anyways, I think we can safely remove the overrides.

**Comment by Zemogiter** [comment]
> What will happen if we do not set it to winxp?

The steam will launch thus allowing user to login and close to let the script continue. The issue is the steam library tab either not working at all (black page) or partially working (page displayed with black rectangles or the page turns to black when scrolling).

**Comment by plata** [comment]
Ok, but like I said this should not be required to install/play games. So let's do it.

**Comment by Zemogiter** [comment]
Closed via #1140
