### ISSUE TITLE
.NET Framework 4.5 fails to install

### ISSUE THREAD

**Issue by Zemogiter** [PhoenicisOrg/scripts#1143]
Can be reproduced by trying to install Space Engineers. I keep gettting this error message and no matter what I click (Abort, Retry, Ignore) it just pops out again. Can't say which line of the `dotnet45` verb is to blame.
![Zrzut ekranu z 2019-11-28 09-55-03](https://user-images.githubusercontent.com/24385408/69791741-6e00d800-11c5-11ea-8e77-eb216339ae37.png)

[wine.log](https://github.com/PhoenicisOrg/scripts/files/3900730/wine.log)

Script repo is up to date, so is the POL5 repo.

**Comment by plata** [comment]
Do you have the same with winetricks?

**Comment by Zemogiter** [comment]
No but it stop when installing dotnet462 with
```
0054:err:ntdll:RtlpWaitForCriticalSection section 0x110060 "../../../dlls/ntdll/heap.c: main process heap section" wait timed out in thread 0054, blocked by 010f, retrying (60 sec)
0057:err:ntdll:RtlpWaitForCriticalSection section 0x110060 "../../../dlls/ntdll/heap.c: main process heap section" wait timed out in thread 0057, blocked by 010f, retrying (60 sec)
0067:err:ntdll:RtlpWaitForCriticalSection section 0x110060 "../../../dlls/ntdll/heap.c: main process heap section" wait timed out in thread 0067, blocked by 010f, retrying (60 sec)
011a:err:ntdll:RtlpWaitForCriticalSection section 0x110060 "../../../dlls/ntdll/heap.c: main process heap section" wait timed out in thread 011a, blocked by 010f, retrying (60 sec)
0060:err:ntdll:RtlpWaitForCriticalSection section 0x110060 "../../../dlls/ntdll/heap.c: main process heap section" wait timed out in thread 0060, blocked by 010f, retrying (60 sec)
0079:err:ntdll:RtlpWaitForCriticalSection section 0x110060 "../../../dlls/ntdll/heap.c: main process heap section" wait timed out in thread 0079, blocked by 010f, retrying (60 sec)
0072:err:ntdll:RtlpWaitForCriticalSection section 0x7beb70a0 "../../../dlls/ntdll/loader.c: loader_section" wait timed out in thread 0072, blocked by 0079, retrying (60 sec)
015a:err:ntdll:RtlpWaitForCriticalSection section 0x7beb70a0 "../../../dlls/ntdll/loader.c: loader_section" wait timed out in thread 015a, blocked by 0079, retrying (60 sec)
```
in loop.

**Comment by madoar** [comment]
I think we need to check all our verbs and plugins if they still function after the "recent" changes to the related APIs. I think I will open an issue for this in the next days.

**Comment by Zemogiter** [comment]
Log file from Space Engineers installation, at the end it makes calls to unimplemented functions in mscoree.dll
[wine.log](https://github.com/PhoenicisOrg/scripts/files/3994378/wine.log)
