### ISSUE TITLE
implement xact_jun2010

### ISSUE THREAD

**Issue by gverm** [PhoenicisOrg/Scripts#116]

**Comment by plata** [comment]
Which applications need this? Is it still required with up to date wine versions?

**Comment by Brainzyy** [comment]
It is, applications like Bully: Anniversary Edition and A Story About My Uncle need it.

**Comment by plata** [comment]
How do you know about "Bully: Anniversary Edition"? I can't even find it on AppDB.

For "A Story About My Uncle" [AppDB](https://appdb.winehq.org/objectManager.php?sClass=version&iId=34524) says you need xact (not xact_jun2010). Doesn't really make a difference implementation wise though. 

Would you mind giving it a try implementing the xact verb? There's a (still very short) article on the [wiki](https://github.com/PlayOnLinux/Scripts/wiki/Verbs). However, if you look at winetricks, you will see the download and cabextracts which have to be done. There's plenty examples of how this is done in the existing verbs. Feel free to enhance the wiki and ask if you need help.

**Comment by Brainzyy** [comment]
@plata This is the game I'm talking about: [https://appdb.winehq.org/objectManager.php?sClass=application&iId=8581](Bully)
And sure, I'll take a stab at it. As far as I know, xact is an old version of xact_jun2010. (I could be wrong)

**Comment by Brainzyy** [comment]
@plata take a look at this bug: [xact bug](https://bugs.winehq.org/show_bug.cgi?id=31476), it is related to the Bully game. Take a look at comment 3.

**Comment by plata** [comment]
@Brainzyy something is broken with your link. Doesn't work when you click it.

Anyways: [AppDb](https://appdb.winehq.org/objectManager.php?sClass=version&iId=33635) doesn't state any verbs for "Bully: Scholarship Edition" with 1.9.8. The bug you mentioned is for wine 1.5.10 (last tests with 1.7.34). I would give it a try with 1.9.23 or even the 2.0-rc.

**Comment by Brainzyy** [comment]
@plata I have tested it with Wine2.0-rc4, bug is still there. And the workaround is "xact_jun2010" as mentioned in comment 3. I have tested it with plain Wine and that fixed it.

**Comment by plata** [comment]
Ok. Strange that the AppDB entry does not mention it.

**Comment by plata** [comment]
@gverm any news on this (i.e. did you succeed in writing a Verb)?

**Comment by ImperatorS79** [comment]
I'm currently trying to implement it.
