### ISSUE TITLE
Wrong method usage in "Mass Effect" Installer

### ISSUE THREAD

**Issue by madoar** [PhoenicisOrg/scripts#1173]
https://github.com/PhoenicisOrg/scripts/blob/5fe4e1f8a9e0f1003e1e9c523c4afb61d15042f7/Applications/Games/Mass%20Effect/Steam/script.js#L12

**Comment by plata** [comment]
Shouldn't ESLint find this kind of issues?

**Comment by madoar** [comment]
No because syntactically speaking this is correct JavaScript syntax. You're passing a function to the `tr` function. The issue is that the `tr` function can't process it correctly. This would either lead to a runtime error or an unexpected output.

**Comment by plata** [comment]
You're right.
