### ISSUE TITLE
Replace "var" with "const" in Age of Empires 2

### ISSUE THREAD

**Issue by madoar** [PhoenicisOrg/scripts#1175]
https://github.com/PhoenicisOrg/scripts/blob/5fe4e1f8a9e0f1003e1e9c523c4afb61d15042f7/Applications/Games/Age%20of%20Empires%20II%20HD/Steam/script.js#L10-L16

**Comment by plata** [comment]
Is AoE II the only script which uses `var`?

**Comment by madoar** [comment]
No I guess not I stumbled over it when searching for `postInstall` occurrences

**Comment by plata** [comment]
We could use https://eslint.org/docs/rules/prefer-const.

**Comment by plata** [comment]
Fixed in #1180.
