### ISSUE TITLE
Update "Space Colony" script

### ISSUE THREAD

**Issue by madoar** [PhoenicisOrg/scripts#1176]
The following should be done:
- change `var` to `const` or `let`
- change `function` to the arrow syntax
- add the missing parameters to `wine.run`

https://github.com/PhoenicisOrg/scripts/blob/5fe4e1f8a9e0f1003e1e9c523c4afb61d15042f7/Applications/Games/Space%20Colony/Local/script.js#L15-L24

**Comment by Zemogiter** [comment]
It's already `const`
