### ISSUE TITLE
Update "Rocksmith" and "Rocksmith 2014" script

### ISSUE THREAD

**Issue by madoar** [PhoenicisOrg/scripts#1178]
The following changes should be done:
- think about inlining the `fixIni` function
- replace `java.awt.Toolkit.getDefaultToolkit().getScreenSize()``with the newer `screenManager`/`virtualDesktop` modules

https://github.com/PhoenicisOrg/scripts/blob/5fe4e1f8a9e0f1003e1e9c523c4afb61d15042f7/Applications/Games/Rocksmith/Steam/script.js#L7-L31

https://github.com/PhoenicisOrg/scripts/blob/5fe4e1f8a9e0f1003e1e9c523c4afb61d15042f7/Applications/Games/Rocksmith%202014/Steam/script.js#L7-L43

**Comment by plata** [comment]
I think it's easier to read the code if `fixIni` is not inline.

**Comment by Zemogiter** [comment]
@plate agreed
