### ISSUE TITLE
GitHub actions JSDoc update

### ISSUE THREAD

**Issue by plata** [PhoenicisOrg/scripts#1233]
We cannot push to master from GitHub actions. If we change the JSDoc in every PR, this will produce conflicts.

**Comment by plata** [comment]
Maybe something like in https://github.com/cycjimmy/semantic-release-action#basic-usage

**Comment by madoar** [comment]
Alternatively we could think about pushing to a separate `jsdoc` branch. In addition this should only activate on pushes to the master branch. Ideally a new PR would be created as well.

**Comment by plata** [comment]
Yes, but this also has some drawbacks. E.g. what happens if the jsdoc branch is not merged before the action wants to create it again? In general, I would like to avoid manual interaction.

**Comment by madoar** [comment]
> E.g. what happens if the jsdoc branch is not merged before the action wants to create it again? In general, I would like to avoid manual interaction.

In this case it should not recreate the `jsdoc` branch instead it should try to update it. If it is needed we could also think about doing a force push to the `jsdoc` branch...
