### ISSUE TITLE
mspatcha download link broken

### ISSUE THREAD

**Issue by SZenglein** [PhoenicisOrg/scripts#1238]
The download link 'https://ftp.gnome.org/mirror/archive/ftp.sunet.se/pub/security/vendor/microsoft/win2000/Service_Packs/usa/W2KSP4_EN.EXE' is not working. Adobe Reader is stuck installing because of this.

A suitable replacement could be 'https://web.archive.org/web/20160129053851if_/http://download.microsoft.com/download/E/6/A/E6A04295-D2A8-40D0-A0C5-241BFECD095E/W2KSP4_EN.EXE'

**Comment by plata** [comment]
Fixed in #1239.
