### ISSUE TITLE
BattlenetScript

### ISSUE THREAD

**Issue by plata** [PhoenicisOrg/Scripts#212]
Implement BattlenetScript (similar to SteamScript).

It is possible to launch Battlenet games via
```battlenet://{ID}```
or 
```battle.net.exe --game={ID} --install```
The ID is wow, d3, wtcg, sc2....

 Determining when the download has finished could be tricky but that can be replaced with a step in the setup wizard ("press next if download finished").

**Comment by ImperatorS79** [comment]
Is it really needed afterall ? Seems all Blizzard games can be downloaded from here [https://eu.battle.net/account/download]( https://eu.battle.net/account/download). There isn't a lot of blizzard games, contrary to Steam or Origin

**Comment by plata** [comment]
If you can download them directly, what's the point of the Blizzard app?

**Comment by ImperatorS79** [comment]
No, the Blizzard app is alaways used. For example, Hearthstone.exe is like a pre-configured version of Blizzars app that will directly download the game.

Blizzard doesn't made a lot of game, so I don't think that make a BattlenetScript is really useful

**Comment by plata** [comment]
I didn't know that you could simply download the game when I wrote this. But yes, makes sense that we do not need it.
