### ISSUE TITLE
Star Wars Jedi Knight II - Jedi Outcast on Linux - __GL_ExtensionStringVersion=17700

### ISSUE THREAD

**Issue by odziom91** [PhoenicisOrg/scripts#213]
Hello!
Is it possible to create shortcuts with any additional declarations before "wine" command?
Some old games - like Star Wars Jedi Knight II - need to run by command:
__GL_ExtensionStringVersion=17700 wine /path/to/your/executable/jk2sp.exe

Other games with the same problem:
Return To Castle Wolfenstein
Kingpin: Life of Crime
Quake 3

**Comment by plata** [comment]
This should be set in the environment. Currently there is no possibility to set it from the outside. I guess we must add a new parameter `environment` to `Wine.prototype.run` (a list of key, value pairs).

**Comment by ImperatorS79** [comment]
Superseded by #869 (more general).
