### ISSUE TITLE
format scripts

### ISSUE THREAD

**Issue by plata** [PhoenicisOrg/Scripts#236]
Use [prettier](https://github.com/prettier/prettier) to format all js files in a common way.

**Comment by madoar** [comment]
Can we somehow perform this automatically?

**Comment by plata** [comment]
Not sure. Maybe Jenkins.

**Comment by plata** [comment]
[StyleCI](https://github.com/marketplace/styleci) could be an option.

**Comment by madoar** [comment]
Is it compatible with the java flavoured javascript?
I think we can just give it a go, if it's not the right solution for us we can change it later on.

**Comment by plata** [comment]
The problem is that it's not free. Actually I think it's too expensive for our needs. Just looking for alternatives.

**Comment by plata** [comment]
Maybe we can use Codacy as well: https://blog.codacy.com/codacy-integrates-with-eslint-6e757b6c802d.

**Comment by madoar** [comment]
What about https://codeclimate.com/?
I'm using codeclimate for a javascript project of mine: https://github.com/madoar/ng2-archwizard

**Comment by plata** [comment]
But it's not free, right?

**Comment by madoar** [comment]
Codeclimate should be free for open source projects.

**Comment by plata** [comment]
Codacy is set up and should ensure that the scripts are formatted correctly.
