### ISSUE TITLE
shortcut miniature missing if app name differs

### ISSUE THREAD

**Issue by plata** [PhoenicisOrg/Scripts#269]
If the name inside the `script.js` is different from the application name, the shortcut miniature is missing (see e.g. "Mafia II (Demo)").

**Comment by madoar** [comment]
This may be related to https://github.com/PlayOnLinux/POL-POM-5/issues/780

**Comment by plata** [comment]
I'm not sure. I think we're just using the wrong name in some places. E.g. also the container will be "Mafia II Demo". In my opinion it would make more sense to use the name from the `application.json` for this.
