### ISSUE TITLE
Option to use one steam installation for everything

### ISSUE THREAD

**Issue by ilgarmehmetali** [PhoenicisOrg/scripts#307]
Instead of having multiple steam installations  requiring updates, having single one would be better for those with slow internet.

**Comment by plata** [comment]
If you want to install multiple games in the same prefix, you can just install Steam and then install the games from Steam. However, we will not support this from the scripts directly because that would defeat the overall idea of using Wine prefixes (you might have conflicting requirements for different games etc.).

Hope this helps.

**Comment by ilgarmehmetali** [comment]
Yes having single prefix for everything might cause some problems but what i meant was having single steam installation somewhere and creating symbolic links to it from newly created prefixes.

Its just i dont see any point in redownloading-updating steam for every prefix. Having different steamapps folders would be just wine.

**Comment by plata** [comment]
Is that possible? I think your Steam has to be in the Wine prefix you use for the game.

**Comment by ilgarmehmetali** [comment]
Creating symbolic link from steam installation to prefix works, i do this to use my steam from windows on my linux.

**Comment by plata** [comment]
Ok. But it's definitely more complicated to maintain etc. (e.g. what to do with Steam if the game is uninstalled?).
To be honest, I don't quite understand the problem of multiple Steam installations regarding slow Internet. If your Internet connection is too slow to download 100-200 MB Steam downloads every now and then, how do you download any game of multiple GB?

**Comment by ilgarmehmetali** [comment]
If there is no other game installed we can remove steam too, otherwise other games will keep using the same steam.

Slow internet was just an example, i dont play all the games on my steam all the time, when i want to play something that i dont play regularly and steam update pops out, it just dampens my mood. Or if you dont have too much free time, 15 minutes of update could ruin your fun.


PS: There are some games that i leave my pc open overnight to download.

**Comment by plata** [comment]
I see. Nevertheless, I don't expect this to happen any time soon if at all. I will leave the decision to @qparis.

**Comment by madoar** [comment]
@plata, doesn't https://github.com/PlayOnLinux/POL-POM-5/pull/929 kind of go in the right direction?
How do you determine there what applications (represented by their shortcuts) are located inside a container?

**Comment by plata** [comment]
I just loop over the shortcuts (`ShortcutDTO`), check their container and collect the shortcuts per container.

**Comment by plata** [comment]
I'm still not completely convinced that this can even work in principle. If you have your Steam somewhere and then link this into your prefix, the Steam download should still download the game to `steamapps` which is in your original Steam installation and not in the prefix (only linked there). So in the end, you would have all games in one Steam linked into several prefixes. Please correct me if I'm wrong.

**Comment by madoar** [comment]
So you basically installed the additional applications through steam and afterwards created a new shortcut for each installed application via the container tab?

**Comment by plata** [comment]
That's what I believe would happen. I guess @ilgarmehmetali can explain how exactly he does it currently.

**Comment by ilgarmehmetali** [comment]
I used to do this with pol4, after installing a game, before game gets downloaded fully i remove the installed steam and create symbolic link.

Having all the steam games in the same directory shouldn't be problem when starting the game with pol shortcut.

If its a problem, a steamapps directory could be created inside the prefix and instead of launching steam directly, a script could be written to create symbolic link for launched app's steamapps directory and then start steam.

```
launcher.sh;

ln -s 
```

**Comment by ilgarmehmetali** [comment]
I used to do this with pol4, after installing a game, before game gets downloaded fully i remove the installed steam and create symbolic link.

Having all the steam games in the same directory shouldn't be problem when starting the game with pol shortcut.

If its a problem, a steamapps directory could be created inside the prefix and instead of launching steam directly, a script could be written to create symbolic link for launched app's steamapps directory and then start steam.

```
launcher.sh;

ln -s 
```

**Comment by ilgarmehmetali** [comment]
I accidentally closed it while writing from my phone.
steamapps could be created inside the prefix.

```
rm $WINEPREFIX/drive_c/Program\ Files/Steam/steamapps
ln -s $WINEPREFIX/steamapps $WINEPREFIX/drive_c/Program\ Files/Steam/steamapps
steam://rungameid/107410
```

**Comment by plata** [comment]
This would have to be implemented in [SteamScript](https://github.com/PlayOnLinux/Scripts/blob/master/Engines/Wine/QuickScript/SteamScript/script.js). If you want to give it a try, feel free to provide a pull request.
There are some basic requirements:
1. It must work automatically (i.e. no user interaction during the installation)
2. It must be optional
3. It must be easy to activate/deactivate (e.g. flag in the install script)

**Comment by plata** [comment]
Closed due to inactivity.
