### ISSUE TITLE
Maybe add developer in the script

### ISSUE THREAD

**Issue by ImperatorS79** [PhoenicisOrg/Scripts#313]
In the different scripts, only editor appears. Sometimes editor and developer are different (example : Battlefield 1 has been developed by DICE, but the editor is EA)

**Comment by plata** [comment]
The question is: Does this information add any value to Phoenicis? I'm not even sure the `editor` is really useful. However, you might argue that we should give some credit to the ones who created the application originally. To be honest I don't see why we should mention the publisher as well.

**Comment by ImperatorS79** [comment]
Yes, actually I thought it was there for some kind of "by editor" search. And then I thought :  "why editor and not developer ?".

Also when you launch an installer, it's written : "This program was created by" which seems to be related to the developer.

But otherwise I agree it's more "cosmetic" than useful

**Comment by plata** [comment]
@ImperatorS79 unless you really want this, I would like to close the issue. I don't think implementing it gives any benefit.

**Comment by madoar** [comment]
@plata Are we currently even using the `editor` field?

**Comment by plata** [comment]
It's only shown when you install the app. Something like "app xyz has been developed by ...".

**Comment by madoar** [comment]
Kk, maybe we should add the editor to the description in the AppPanel too?

**Comment by plata** [comment]
We could do that.

**Comment by plata** [comment]
Can you open a new issue in POL-POM-5 if you want to have it?
