### ISSUE TITLE
Age of Empires II HD doesn't create a launcher on install

### ISSUE THREAD

**Issue by Ads20000** [PhoenicisOrg/Scripts#324]
After installing Age of Empires II HD, no launcher was created for me to click on in Library (I don't get a launcher in the Unity Dash either). I got an error that came up after I installed it, but I don't know where Phoenicis logs are stored so I can't find that. Bug could've been introduced by #234 which was to fix a bug I previously filed. However, AoE II HD doesn't even load when launching the launcher manually, as you can see in #325.

**Comment by plata** [comment]
Did it create files in the shortcut directory (usually `~/.Phoenicis/shortcuts`)?

**Comment by Ads20000** [comment]
No. Also should I report a separate bug for the logs issue or is there a location you can give me for that? :)

**Comment by plata** [comment]
It created the shortcuts for me.

**Comment by Ads20000** [comment]
Which is why it would be nice to have the error log to see what went wrong in my case..... xD

**Comment by plata** [comment]
Sure. Until we have that: can you run it again and check the console output (maybe in your IDE)?

**Comment by Ads20000** [comment]
I'm afraid not. I installed it when I was somewhere else with good Internet but I don't have that now. Could test next Friday if you remind me! :)

**Comment by plata** [comment]
Too bad. I hope we can fix the logs issue soon.

**Comment by ImperatorS79** [comment]
For the wine logs, I have changed in a local repo all the values of WINEDEBUG in the scripts from "-all" to "", and I launch POL5 with `./phoenicis.sh ` (if it is your log problem)

**Comment by plata** [comment]
@Ads20000 can you verify that this is still valid?

**Comment by plata** [comment]
Closed due to inactivity. Please open a new issue if there are still problems.
