### ISSUE TITLE
Age of Empires II HD error when trying to Run executable

### ISSUE THREAD

**Issue by Ads20000** [PhoenicisOrg/Scripts#325]
Further to #324 , I can't even run `Launcher.exe` manually. I get the error `wine: cannot find L"C:\\windows\\system32\\winemenubuilder.exe"`.

Trying to launch `AoK HD.exe` gives me a few more windows (says it's Connecting Steam account and then preparing to launch AoE) but still no luck, the output for that is:

```
wine: cannot find L"C:\\windows\\system32\\winemenubuilder.exe"
p11-kit: couldn't load module: /usr/lib/i386-linux-gnu/pkcs11/p11-kit-trust.so: /usr/lib/i386-linux-gnu/pkcs11/p11-kit-trust.so: cannot open shared object file: No such file or directory
p11-kit: couldn't load module: /usr/lib/i386-linux-gnu/pkcs11/gnome-keyring-pkcs11.so: /usr/lib/i386-linux-gnu/pkcs11/gnome-keyring-pkcs11.so: cannot open shared object file: No such file or directory
p11-kit: couldn't load module: /usr/lib/i386-linux-gnu/pkcs11/p11-kit-trust.so: /usr/lib/i386-linux-gnu/pkcs11/p11-kit-trust.so: cannot open shared object file: No such file or directory
p11-kit: couldn't load module: /usr/lib/i386-linux-gnu/pkcs11/gnome-keyring-pkcs11.so: /usr/lib/i386-linux-gnu/pkcs11/gnome-keyring-pkcs11.so: cannot open shared object file: No such file or directory
```

Ubuntu 17.04 64-bit

**Comment by ImperatorS79** [comment]
I have never seen any program blocked by those errors.

You can certainly solve the p11-kit error with : 

`sudo apt-get install p11-kit-modules:i386`

You could do the same thing for gnome-keyring, but I obtain :

> The following packages contain unfulfilled dependencies:
Gnome-keyring: i386: Depends: gcr: i386 (> = 3.4) plus will not be installed
Depends: pinentry-gnome3: i386 plus will not be installed
E: Unable to fix problems, defective packages are in "keep as is" mode.

 `


`

**Comment by madoar** [comment]
@Ads20000 can you give us some information about your used OS?

**Comment by plata** [comment]
Btw: This menubuilder error should not be a problem.

**Comment by Ads20000** [comment]
@madoar Ubuntu 17.04 64-bit, sorry, that should've been in the bug description

**Comment by plata** [comment]
Could you try to run from command line with plain wine?

**Comment by Ads20000** [comment]
[Paste for the output](http://paste.ubuntu.com/25339175/)

I didn't install Mono or Gecko when it asked me to, my Internet being too rubbish, do I need to install those?

**Comment by plata** [comment]
Your command should look like this: 
```
WINEPREFIX="/home/adam/.Phoenicis/wineprefix/Age of Empires II HD" /home/adam/.Phoenicis/engines/wine/upstream-linux-x86/2.0.2/bin/wine "/home/adam/.Phoenicis/containers/wineprefix/Age of Empires II HD/drive_c/Program Files/Steam/Steam.exe" -silent -applaunch 221380
```

**Comment by Ads20000** [comment]
Thanks for the command! Steam opened a window saying that it was preparing to launch AoE II HD but silently failed (didn't give a graphical error message or quit the Terminal command (I hit <kbd>Ctrl</kbd>+<kbd>C</kbd> twice to quit it). I had left it for 15 minutes (before hitting <kbd>Ctrl</kbd>+<kbd>C</kbd>) to see if it would load eventually but it didn't).

I think the error is:
```
err:module:import_dll Library mfc140u.dll (which is needed by L"C:\\Program Files\\Steam\\steamapps\\common\\Age2HD\\Launcher.exe") not found
err:module:LdrInitializeThunk Main exe initialization for L"C:\\Program Files\\Steam\\steamapps\\common\\Age2HD\\Launcher.exe" failed, status c0000135
```

[Full Terminal ouput](http://paste.ubuntu.com/25339283/)

**Comment by plata** [comment]
Can you run "verify local files" in Steam?

**Comment by Ads20000** [comment]
'All files successfully validated.' :)

**Comment by plata** [comment]
Mh. This mfc140u.dll belongs to vcrun2015. Do you have any dll overrides set?

**Comment by plata** [comment]
It should be in `windows/system32`.

**Comment by Ads20000** [comment]
There's no overrides for that container... one for vcrun2015 should've been set by the script though?

**Comment by plata** [comment]
The script doesn't set any overrides. I don't know why you're missing that dll. I guess it should be installed during the first time installation of AoEII HD. You can try to repeat that install step manually
```
WINEPREFIX="/home/adam/.Phoenicis/wineprefix/Age of Empires II HD" /home/adam/.Phoenicis/engines/wine/upstream-linux-x86/2.0.2/bin/wine "/home/adam/.Phoenicis/wineprefix/Age of Empires II HD/drive_c/Program Files/Steam/steamapps/common/Age2HD/_CommonRedist/vcredist/2015/vc_redist.x86.exe"
```
or install vcrun2015 with winetricks
```
WINEPREFIX="/home/adam/.Phoenicis/wineprefix/Age of Empires II HD" winetricks --force vcrun2015
```

**Comment by plata** [comment]
If it works after that and you can reproduce that this dll is missing, we can consider to install vcrun2015 from the script directly.

**Comment by Ads20000** [comment]
The first command [didn't seem to work](http://paste.ubuntu.com/25339762/)

**Comment by plata** [comment]
Try
```
export PATH="/home/adam/.Phoenicis/engines/wine/upstream-linux-x86/2.0.2/lib":$PATH
WINEPREFIX="/home/adam/.Phoenicis/wineprefix/Age of Empires II HD" /home/adam/.Phoenicis/engines/wine/upstream-linux-x86/2.0.2/bin/wine "/home/adam/.Phoenicis/wineprefix/Age of Empires II HD/drive_c/Program Files/Steam/steamapps/common/Age2HD/_CommonRedist/vcredist/2015/vc_redist.x86.exe"

**Comment by Ads20000** [comment]
The first command executes and then launching AoE II HD still [doesn't work](http://paste.ubuntu.com/25346171/).

```
err:module:import_dll Library mfc140u.dll (which is needed by L"C:\\Program Files\\Steam\\steamapps\\common\\Age2HD\\Launcher.exe") not found
err:module:LdrInitializeThunk Main exe initialization for L"C:\\Program Files\\Steam\\steamapps\\common\\Age2HD\\Launcher.exe" failed, status c0000135
```

(same error as before)

Installing via winetricks gets me further. This time the application loaded the window you've screenshotted me before (rather than the full-screen game) but was very unusable. Tried loading it again, twice, but this time I just got a Wine crash window. [Terminal output](http://paste.ubuntu.com/25346244/).

![screenshot from 2017-08-19 11-29-59](https://user-images.githubusercontent.com/3178485/29485933-16198730-84d3-11e7-9d30-fdfb847794c4.png)

**Comment by Ads20000** [comment]
This worked fine in POL 4 so I'm still blaming Phoenicis or the script for what's going wrong here rather than Wine.

**Comment by plata** [comment]
It still has this `libpng` issue. Did you set the `PATH` when running from command line like I wrote above?

**Comment by Ads20000** [comment]
Tried setting the PATH before running it (and did the `PATH` thing for the non-winetricks attempt to install the dll too). This time I got the non-fullscreen window and the error window. [Log](http://paste.ubuntu.com/25346309/). Did you mean I needed to set the `PATH` before using `winetricks`? Because I'm not sure I did that :/

**Comment by plata** [comment]
No, not before `winetricks`. Can you check if there is a `libpng.12.so.0` in `/home/adam/.Phoenicis/engines/wine/upstream-linux-x86/2.0.2/lib` (it should).

**Comment by Ads20000** [comment]
It's there 
![screenshot from 2017-08-19 12-01-57](https://user-images.githubusercontent.com/3178485/29486107-400c4a5c-84d6-11e7-9f84-363775dd73c4.png)

**Comment by plata** [comment]
I don't understand it. Why can't it find the .so if it's obviously there?

**Comment by plata** [comment]
@Ads20000 is this issue still valid?
