### ISSUE TITLE
Add a note field to the scripts

### ISSUE THREAD

**Issue by madoar** [PhoenicisOrg/scripts#361]
Currently we can't differentiate between the reasons for why a script is marked as `testing`.
This could be, because of multiple reasons. For one the script could simply be untested, another reason could be that the script is not working, or has some quirks.
To capture these reasons, and make them visible to the end user, we should provide an optional field to the script called `note`, where the script author can describe the reason why the script is marked as testing. Alternatively we could think about adding a `note` field for each of the testing OSes. This would be useful in case the script has different quirks on linux than on mac.
This `note` field should also be visible in the installation wizard of the script to inform the user.

**Comment by plata** [comment]
Should this be in the .js or .json?

**Comment by madoar** [comment]
Ideally I would like to extend the `script.json` file to look like:

```json
{
	"scriptName": "BETA Client",
	"compatibleOperatingSystems": ["MACOSX", "LINUX"],
	"testingOperatingSystems": [{ os: "MACOSX", msg: "Doesn't install", { os: "LINUX", msg: "Doesn't run after installation" }],
	"free": true,
	"requiresPatch": false
}
```
in case the message is the same for all test operating systems, we could support something like:

```json
{
	"scriptName": "BETA Client",
	"compatibleOperatingSystems": ["MACOSX", "LINUX"],
	"testingOperatingSystems": [{ os: ["MACOSX", "LINUX"] , msg: "Doesn't install" }],
	"free": true,
	"requiresPatch": false
}
```

In case we have no message we could let it remain as is:

```json
{
	"scriptName": "BETA Client",
	"compatibleOperatingSystems": ["MACOSX", "LINUX"],
	"testingOperatingSystems": ["MACOSX", "LINUX"],
	"free": true,
	"requiresPatch": false
}
```

**Comment by plata** [comment]
I see two problems:
1. Can this be parsed into the `ScriptDTO` automatically?
2. Where should the information be shown? We have the information in the `AppPanel` but I don't know how we could show it there. If we want to show it in the wizard, we have to add a step for each and every wizard which is error prone (someone might forget this).

**Comment by madoar** [comment]
About your problems:

1. I don't know, this is just how I would wish the code to be structured. If this is not possible we need to find some other solution or take some limitations in account.
2. Can't we show this information in the same step as the editor? I wouldn't add it to the `AppPanel`, because the `AppPanel` can contain multiple scripts, this would require to add a selection mechanism for scripts, to show related details, right?

**Comment by plata** [comment]
2. Can we access the .json for the .js? And even if we can: Will anybody notice this if we add it to the presentation step (at least I always skip it without really reading)?

**Comment by madoar** [comment]
We should be able to access the .json file from inside the .js file via a `require`.
The largest problem would be to show the message to the user in the right way.

**Comment by plata** [comment]
I don't think we can use `require`. We have to use the .json from the repository not from the file system.

**Comment by plata** [comment]
Maybe we should name the field `description`. We can then use it in the `ShortcutDTO`.
