### ISSUE TITLE
Add a way to have multiple shortcuts for one script

### ISSUE THREAD

**Issue by ImperatorS79** [PhoenicisOrg/Scripts#362]
Example : MS Office which install Word, Excel, PowePoint ...

**Comment by plata** [comment]
I think that's possible already.

**Comment by ImperatorS79** [comment]
I wasn't aware of this (maybe add it in the wiki then ?)

**Comment by plata** [comment]
Where should I describe it?

In the end you have to call:
```
new WineShortcut()
    .name(application)
    .prefix(application)
    .search("application.exe")
    .miniature(["category", application])
    .create();
```

**Comment by ImperatorS79** [comment]
OK I should be a little more careful. Sorry for disturbance

**Comment by plata** [comment]
No problem. I agree that it's not really obvious.
