### ISSUE TITLE
update latest Wine version automatically

### ISSUE THREAD

**Issue by plata** [PhoenicisOrg/scripts#445]
Currently we update LATEST_DEVELOPMENT_VERSION and LATEST_STAGING_VERSION manually. It should be possible to automate this, i.e. update whenever a new version is available.

**Comment by madoar** [comment]
You're right about that. The question is, how should this be done?
I believe the final way will be to query the latest versions from the online repository, which we'll need, when Phoenicis 5 will be released. Can we introduce an intermediate solution, or maybe find a better way to solve this problem?

**Comment by plata** [comment]
There's the `availableVersions()` function already. We could introduce two functions `latestDevelopmentVersion()` and `latestStagingVersion()` instead of the variables LATEST_DEVELOPMENT_VERSION and LATEST_STAGING_VERSION. So instead of
```Javascript
    .wineVersion(LATEST_STAGING_VERSION)
```
we would have
```Javascript
    .wineVersion(this.latestStagingVersion())
```
.
`latestDevelopmentVersion()` would e.g. call `availableVersions("upstream-linux-x86")` and then sort the result (keep in mind PhoenicisOrg/POL-POM-5#935).

If we do this, we will have the code to sort the versions twice: in JS and the `Comparator` in `EngineSubCategoryDTO`. We should (in the future) implement the sorting only in JS but this is more the "generic engines" topic already.

**Comment by madoar** [comment]
Do you know if nashorn supports javascript getters? (See also here: https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Functions/get)

**Comment by plata** [comment]
I don't know. Would be nice. Can you try it?

**Comment by madoar** [comment]
A test with `jjs` indicates, that getter methods work in nashorn.

**Comment by plata** [comment]
Ok. Do you want to try it for `latestDevelopmentVersion()` and `latestStagingVersion()` (you could just return `LATEST_DEVELOPMENT_VERSION` or `LATEST_STAGING_VERSION` for now)?

**Comment by madoar** [comment]
I think we're not talking about the same idea^^

My suggestion would be to change the current constant implementation to something like this:

```javascript
get LATEST_STABLE_VERSION() {
    return "2.0.2";
};

get LATEST_DEVELOPMENT_VERSION() {
    return "2.18";
};

get LATEST_STAGING_VERSION() {
    return "2.18";
};
```

This currently won't work, because javascript only accepts getters inside json objects or classes, i.e. something like this should work:

```javascript
var state = {
    get LATEST_STABLE_VERSION() {
        return "2.0.2";
    },
    get LATEST_DEVELOPMENT_VERSION() {
        return "2.18";
    },
    get LATEST_STAGING_VERSION() {
        return "2.18";
    }
};
```

**Comment by plata** [comment]
We have the `Wine` class already. So why should we add a new `state` class instead of adding it to `Wine` directly?

**Comment by plata** [comment]
Ok. I forgot something. We cannot have it in the `Wine` object because we cannot access it (it doesn't even exist at that time). We could, however, put it to the (new) `WineUtils` class where also the `getAvailableVersions` should be located.

**Comment by madoar** [comment]
Yes, that sounds like a good idea

**Comment by plata** [comment]
Maybe this information should be available in the Wine versions JSON. It doesn't help if the latest stable version is not available in the Wine versions source you are using (e.g. Lutris).

**Comment by plata** [comment]
Apparently it is possible to fetch the versions from the versions JSON (see https://github.com/PhoenicisOrg/phoenicis-winebuild/issues/77). However, I'm not sure if that's an approach we can follow: If the versions JSON cannot be downloaded (e.g. because you are offline), you would not be able to install any app. Currently this is possible if the required Wine version is installed already.

**Comment by madoar** [comment]
> However, I'm not sure if that's an approach we can follow: If the versions JSON cannot be downloaded (e.g. because you are offline), you would not be able to install any app. Currently this is possible if the required Wine version is installed already.

Can't we cache the previously fetched JSON file for the case that we can't download it later on? This should solve the issue, right? We could also add a hardcoded fallback, the problem here is again that we would need to update it later on manually...

**Comment by plata** [comment]
We have to check if the `Downloader` knows whether or not the URL is reachable. I've just tried to specify an invalid URL but that didn't cause an error. Instead, it created an `availableVersions.json` containing "Error".
