### ISSUE TITLE
Custom wine versions requested by users

### ISSUE THREAD

**Issue by ImperatorS79** [PhoenicisOrg/scripts#459]
Those wine versions have been requested here [https://www.playonlinux.com/fr/bugs.html](https://www.playonlinux.com/fr/bugs.html):

-Wine 2.20 (and staging) for macOS beta -> [https://bugs.winehq.org/show_bug.cgi?id=43966](https://bugs.winehq.org/show_bug.cgi?id=43966 (fix here))
-Wine 2.20-staging with fallout 4 hack -> [https://bugs.winehq.org/show_bug.cgi?id=41271](https://bugs.winehq.org/show_bug.cgi?id=41271)
-Wine 2.20-staging with wolfentein 2 hack -> [https://bugs.winehq.org/show_bug.cgi?id=43935](https://bugs.winehq.org/show_bug.cgi?id=43935).

**Comment by plata** [comment]
I think this should be in PhoenicisOrg/POL-POM-5 or PhoenicisOrg/WineBuild. @qparis is the only one who can do it.

**Comment by ImperatorS79** [comment]
I close this because wine has move forward and those wine version are outdated
