### ISSUE TITLE
Error during Steam installation + missing sound

### ISSUE THREAD

**Issue by madoar** [PhoenicisOrg/scripts#462]
I'm currently writing a new script for the game [Alien Swarm](http://store.steampowered.com/app/563560/Alien_Swarm_Reactive_Drop/), which can be found [here](https://github.com/madoar/Scripts/tree/alien-swarm).
When testing the new script I stumbled over multiple problems:

1. When installing steam I get the following error message:
![auswahl_020](https://user-images.githubusercontent.com/18488086/33402062-ae8c3aca-d55b-11e7-9b5a-9c35724328b5.png)
   Luckily this message is ignorable, and can be closed without terminating the installation.
2. Afterwards I've discovered, that I had no sound in the game. This lead me to the wine configuration and Regedit to take a look at the sound configuration of wine, which looks like this:
![auswahl_021](https://user-images.githubusercontent.com/18488086/33402125-deac64fa-d55b-11e7-9d93-df7f65cf7b57.png)
![auswahl_022](https://user-images.githubusercontent.com/18488086/33402126-e04fda12-d55b-11e7-98fd-c5d336b554cc.png)
   As far as I know, the wine configuration should at least show a selected driver, which in my screenshot is `none` (Kein).
   In addition, as far as I understand https://wiki.winehq.org/Sound, a registry entry `HKEY_CURRENT_USER\Software\Wine\Drivers` should exist, which should contain at least the sound driver settings.

Do you have any idea how to fix these issues?

**Comment by plata** [comment]
Is there any bug report on winehq about this? At a first glance this looks like a Wine problem to me (wouldn't know how Phoenicis should cause this).

Regarding the webhelper: Can you solve it if you run steamwebhelper.exe with winxp?

**Comment by madoar** [comment]
I don't know of a bug report regarding sound problems in combination with wine and alien swarm.
Maybe you could test if you stumble over the same problem? I mean the game is free and I believe you don't even need to completely install it, because the wine settings in my case show, that no drivers are available...
Regarding webhelper: Here it seems like a change to `winxp` helps.

**Comment by plata** [comment]
Just tried. I have sound.

**Comment by madoar** [comment]
Kk, then it seems to be my setup.
Do you have an idea how to elegantly fix the webhelper problem? I'm not sure if it's a good idea to completely set the windows version to `winxp` inside the script.

**Comment by plata** [comment]
We could set webhelper to winxp in the SteamScript directly.

**Comment by madoar** [comment]
Can you do a PR? I have no idea how to do this specifically for webhelper.

**Comment by plata** [comment]
I have no time to test this currently. But in the end it's pretty easy. Compare e.g. in the Rocksmith 2014 script:
```Javascript
wine.setOsForApplication().set("Rocksmith2014.exe", "win7").do();
```

**Comment by madoar** [comment]
@plata I'll test it tomorrow.

**Comment by plata** [comment]
@madoar can we close this?

**Comment by madoar** [comment]
I have no clue.
But I think it is possible that the reason for this were some missing system dependencies at the time.
So let's close this for now.
