### ISSUE TITLE
Origin error

### ISSUE THREAD

**Issue by ivanlogiudice** [PhoenicisOrg/scripts#465]
Can't connect to origin

![Origin](https://i.imgur.com/OJYif54.png)

**Comment by ImperatorS79** [comment]
Which script did you use ? Legacy or not legacy ? Can you share the wine.log file inside the prefix ?

**Comment by plata** [comment]
The error you highlighted is probably PhoenicisOrg/POL-POM-5#1144. It is not really a problem. The real issue is the crash of OriginWebHelperService.exe. This is a known Wine bug (see [Bug 43187](https://bugs.winehq.org/show_bug.cgi?id=43187)).

**Comment by madoar** [comment]
@plata as far as I know you've fixed https://github.com/PhoenicisOrg/POL-POM-5/issues/1144, can we close this too?

**Comment by plata** [comment]
I don't think so. The real problem is the Wine bug (see [Bug 43187](https://bugs.winehq.org/show_bug.cgi?id=43187)). PhoenicisOrg/POL-POM-5#1144 wasn't related to the problem at all.

**Comment by Zemogiter** [comment]
It runs just fine when installed and launched from Lutris instead of normal Wine or POL/POL5. Something in their framework bypasses that wine bug. Sadly I don't know how to implement that to POL5/POM5 Origin script.
https://lutris.net/games/origin/
FYI I was using the newer Lutris script from the link above (rated Gold).

**Comment by plata** [comment]
Did you look at https://lutris.net/games/install/6890/view ?

I don't really now how Lutris works/how they build Wine. However, I got in touch with them. Maybe we can collaborate for issues like this (we are facing the same issues).

**Comment by Zemogiter** [comment]
@plata yes that is the Lutris script I used

**Comment by plata** [comment]
I know, that's why I asked. I didn't check if our script uses the same wine version etc.

**Comment by plata** [comment]
Origin should be working now. I will close this.

If you still experience issues, feel free to reopen or create a new issue.
