### ISSUE TITLE
32bit Wine support

### ISSUE THREAD

**Issue by plata** [PhoenicisOrg/scripts#537]
Do we want to continue supporting the 32bit Wine version?

* some distributions are already 64bit only (elementary OS, Solus...)
* macOS is dropping 32bit support (I already couldn't manage to build 32bit Wine with Travis now - see https://github.com/plata/wine-builds)
* Ubuntu 18 will not provide 32bit installers (see [release notes](https://wiki.ubuntu.com/BionicBeaver/ReleaseNotes))
* same for Tails (see [announcement](https://tails.boum.org/news/Tails_3.0_will_require_a_64-bit_processor/index.en.html)), Arch (since 2017.03.01) and probably many more

I therefore propose to drop support for 32bit Wine installations and use the `architecture` to set `WINEARCH` during prefix creation (see [How do I create a 32 bit wineprefix on a 64 bit system?](https://wiki.winehq.org/FAQ#How_do_I_create_a_32_bit_wineprefix_on_a_64_bit_system.3F)).

**Comment by plata** [comment]
This would implicitly solve #379.

**Comment by madoar** [comment]
As long as we this doesn't prevent us from installing 32bit applications I think we can give it a try.
@qparis what do you think?

**Comment by ImperatorS79** [comment]
But you will still need 32 bits deps to launch 32 bits apps (and built biarch wine, instead of 32/64 separately), so that will not fix the mac os problem.

**Comment by ImperatorS79** [comment]
And it seems that the old builder of POL/POM is still working well for macOS 32bits

**Comment by plata** [comment]
@ImperatorS79 the 32bit runtime dependencies is true. However, that's a general issue (also for Wine) of which I don't know how it shall be solved. For example, homebrew is also removing the 32bit support so where do you get the dependencies from?

Regarding the old builder: This is also correct. But: the setup to do this is rather weird (to say the least). Here's a quote from @qparis about how it is done.

> One of them contains the tool chain to cross compile on OSX (which is a bit tricky ; requires to take some files from an Apple computer and also requires to recompile the compiler itself with mshook_prologue support)

This is also one of the reasons why I'm trying to get rid of that old builder and replace it by something better maintainable (e.g. Travis).

**Comment by ImperatorS79** [comment]
Some info here -> [https://bugs.winehq.org/show_bug.cgi?id=45057](https://bugs.winehq.org/show_bug.cgi?id=45057)

**Comment by plata** [comment]
This sounds like using Wine 64bit to run 32bit apps has some problems. Any more detailed info on that?

**Comment by qparis** [comment]
So, is this issue still valid? 

Basically the point of the question is still valid: How do we run 32bits app with 64bits wine (it will be required on OSX). However the question of the new builder is now solved

**Comment by plata** [comment]
I don't know. We can leave this issue open or create a new one for the stuff you mentioned. Whatever you prefer.

**Comment by ImperatorS79** [comment]
IMHO, the issue to run 32 bits apps on macOS has to be solved on the wine side. And I think there are already looking after that ([https://bugs.winehq.org/show_bug.cgi?id=45057](https://bugs.winehq.org/show_bug.cgi?id=45057), comment 2).

**Comment by plata** [comment]
Makes sense to me. So we can close this.
