### ISSUE TITLE
Decide whether "free" and "requiresPatch" are needed for verbs

### ISSUE THREAD

**Issue by madoar** [PhoenicisOrg/scripts#545]
See #542 for more details

**Comment by plata** [comment]
I think it makes sense to have:
* It is better to specify it explicitly than assuming something implicitly.
* A Verb could be non free in principle.
* A Verb could require a patch to run properly.
* If we treat Verbs as first class citizens there's no reason to use a different json than for an application.
* People might wonder why the `script.json` looks differently for Verbs and applications.

**Comment by madoar** [comment]
How should we use the `free` and `requiresPath` fields?
I mean for normal application scripts we have a filter mechanism in the GUI, but for verbs I don't think we require such a mechanism.

**Comment by plata** [comment]
I'm not sure. It would be good if we could somehow show the dependencies of a script. Then we could warn about non-free Verbs or Verbs which require a patch. However, I have absolutely no idea currently how something like that could work.

**Comment by plata** [comment]
@madoar I would suggest to close this as "won't fix". In my opinion we should not add any differentiation to the verbs (i.e. they should be agnostic of their type as far as possible).

**Comment by madoar** [comment]
I agree that we shouldn't differentiate between verbs and other kinds of scripts (like installation scripts).
I think the problem currently is that we collect this information for verbs and other kind of scripts, but don't use it.

I think we should talk about how we want to use the `free` and `requiresPatch` for verbs and other kinds of scripts.

**Comment by plata** [comment]
We could add filters like for apps. As we don't have any non-free verbs currently, I think we should just close this and discuss the topic again if it should become relevant.

**Comment by madoar** [comment]
I don't think it is so easy, because the `free` and `requiresPatch` of the used verbs for an application install script influence the `free` and `requiresPatch` values of the application install script itself.
The issue is that we don't reflect this and I don't know how we should handle this at all, therefore my idea was to remove this information for now.

**Comment by plata** [comment]
> the free and requiresPatch of the used verbs for an application install script influence the free and requiresPatch values of the application install script itself
That's correct. Nevertheless: it's only a hypothetic case right now and I don't think it makes sense to remove the fields and then add them again later. So if we cannot come to a decision, we should maybe just keep this open.

**Comment by plata** [comment]
Closed because we will not handle this anytime soon.
