### ISSUE TITLE
idea: engine plugins

### ISSUE THREAD

**Issue by plata** [PhoenicisOrg/scripts#604]
Implement everything except the engine core functionality as plugin. A plugin is implemented similarly to a verb. For example, we would have an `overrideDll` plugin.

The advantage of this would be:
* not one gigantic Wine script
* other repositories can easily add/replace plugins (this fits very well into our general concept)

**Comment by madoar** [comment]
This sounds like a great idea!
How do you want to register the plugins at the engine?
I see two possibilities:

1) we can use our current mixin approach, where each plugin extends the engine prototype
2) we can add a field/method `plugins` to the Java interface/class which allows the registration and access of plugins to an engine

**Comment by plata** [comment]
The original idea was 1.

The 2. sounds interesting but I'm currently unsure if/how it could work. Could you describe a bit more detailed what you have in mind?

**Comment by madoar** [comment]
The generic idea is the following:

First we would need two Java interfaces:

```java
public interface Engine {
   void registerPlugin(EnginePlugin plugin);

   EnginePlugin getPlugin(String pluginIdentifier);
}

public interface EnginePlugin {
   void execute(Object... parameters);
}
```

Every engine plugin needs to implement the `EnginePlugin` interface, while every engine needs to implement the `Engine` interface.

When writing an application script, the plugins are "injected" via the already known `include` command.
`include` will automatically create an `EnginePlugin` instance and add it should also (somehow) add it to the engine via `engine#registerPlugin`.

To access a plugin inside an engine hook, you can then use `engine.getPlugin("pluginIdentifier").execute(parameters);`.

**Comment by madoar** [comment]
Then as an alternative we could do the registration inside the `engine#getPlugin` method,
i.e. the implementation of `engine#getPlugin` would look similar to this:

```java
public EnginePlugin getPlugin(String identifier) {
   ...
   this.registerPlugin(newPlugin)
   ...
   return newPlugin;
}
```

Then we wouldn't need the plugin includes at the beginning anymore.

**Comment by plata** [comment]
Any solution for the second issue I've described?

**Comment by madoar** [comment]
In general I think we should define the `execute` method as generic as possible, but I don't have a clear solution for the second problem.

What we could do is to define the `execute` method to have a return value of type `Object`, but what happens then with plugins, that return void?

**Comment by plata** [comment]
Mh. To be honest, I currently prefer to do it the same way as verbs.

**Comment by madoar** [comment]
You're right, we should do it the same way as we implement the verbs.

The idea is rather meant as an alternative approach to how we do things now.
Just something to think about, maybe we can think of a better approach :)
