### ISSUE TITLE
Check dll destination on 64 bits wine

### ISSUE THREAD

**Issue by ImperatorS79** [PhoenicisOrg/scripts#695]
On windows 32 bits, dll's go to system32.
On windows 64 bits, 32 bits dll's go to syswow64 and 64 bits ones to system32.

**Comment by madoar** [comment]
I'm not the biggest operating system expert, but it seems to me, that you've switched the folders for windows 64bits.
Shouldn't it be 32bit dlls go to system 32 and 64bit dlls go to syswow64?

About which scripts are we talking?
The wine script itself or other verbs, which extend the wine script?

**Comment by ImperatorS79** [comment]
It seems confusing but it is like that, see VK9 for example ([https://github.com/disks86/VK9/wiki/Installation-Instructions-(Linux)](https://github.com/disks86/VK9/wiki/Installation-Instructions-(Linux)).

Seems that it's handled in phoenicis (I did not know that, so I'll will have to change my scripts) :
```js
/**
*
* @returns {string} system32 directory
*/
Wine.prototype.system32directory = function () {
    if (fileExists(this.prefixDirectory() + "/drive_c/windows/syswow64")) {
        return this.prefixDirectory() + "/drive_c/windows/syswow64";
    } else {
        return this.prefixDirectory() + "/drive_c/windows/system32";
    }
};

/**
*
* @returns {string} system64 directory
*/
Wine.prototype.system64directory = function () {
    if (fileExists(this.prefixDirectory() + "/drive_c/windows/syswow64")) {
        return this.prefixDirectory() + "/drive_c/windows/system32";
    }
    throw tr("Prefix seems to be 32bits");
};
```
I'll just have to check my scripts (like dxvk, vk9, xact) but maybe others are affected

**Comment by plata** [comment]
This is weird:
```Javascript
if (fileExists(this.prefixDirectory() + "/drive_c/windows/syswow64")) {
    return this.prefixDirectory() + "/drive_c/windows/system32";
}
```

**Comment by ImperatorS79** [comment]
You just have to ensure, when you are copying dlls to /windows/smth directory, that 32bits dlls goes to system32 for a 32 bits prefix and syswow64 for a 64bits one (64 bits dll always go to system32).

This already handled if you are using `system32directory ` for 32 bits dll and `system64directory` for 64 bits dll. I was not aware of that when I made those scripts (and did the check one more time -> wrong).

Maybe you should precise this somewhere in the doc.

**Comment by plata** [comment]
@ImperatorS79 do you want to propose a PR for the doc?
