### ISSUE TITLE
PoL 4 scripts

### ISSUE THREAD

**Issue by t0msk** [PhoenicisOrg/scripts#715]
Hello, I would like to know, where I can find installation scripts from PoL 4, or if they are hidden, could be released?

To be more specific, I would like to see installation script of StarCraft 1

**Comment by qparis** [comment]
POLv4 scripts are not supported on POLv5

**Comment by plata** [comment]
@t0msk it should be rather either to port the PoL4 script to Phoenicis.

**Comment by t0msk** [comment]
@qparis I know that it is not supported, I just want to see what is inside of this script for StarCraft, because I want to install it using Phoenicis.

**Comment by t0msk** [comment]
Thanks :)
