### ISSUE TITLE
Add Winetricks into Engine tools

### ISSUE THREAD

**Issue by t0msk** [PhoenicisOrg/scripts#716]
When you open Engine tools in Container, there could be button which launch winetricks in currently selected container.

I know, I can open a terminal and launch winetricks from here, but it should much more user friendly if there was button for it, because it is quite fundamental thing and it would be much quicker to access it from button than from console.

**Comment by qparis** [comment]
We tried to integrate winetricks to POLv4 before and we decided not to use it. 
We are already providing wine verbs through our scripts repository, these verbs should be installation from Engine Tools

**Comment by plata** [comment]
To be clear: We will not provide this in the official repository but of course you are free to create your own repository with a winetricks tool.

**Comment by t0msk** [comment]
@qparis But you don't provide to install verbs to existing containers --> https://github.com/PhoenicisOrg/phoenicis/issues/1440

**Comment by plata** [comment]
Not yet.

**Comment by t0msk** [comment]
@qparis @plata I just wonder why you don't want to have Winetricks shortcut in Engine tools? It would help and it is little code to implement it.

**Comment by qparis** [comment]
Implementing a winetricks shortcut in engine tool is not easier than doing directly the ticket #1440.  However, the problem with winetricks was too be able to provide support to the community: once a winetricks verb is installed into a prefix, it can radically change its behavior and we don't necessary know what version of winetricks was used...

On the other hand, now that winetricks is maintened by Austin English, this might have changed a little bit...

**Comment by plata** [comment]
So shall we do it or not?

**Comment by qparis** [comment]
The priority is #1440. Then we might decided to encapsulate winetricks verbs in javascript. What do you think?

**Comment by plata** [comment]
I think we have a different understanding. I understood @t0msk in a way that we implement a tool which simply opens winetricks (and not to encapsulate winetricks verbs).

**Comment by qparis** [comment]
Yup, but I think that we should not support directly winetricks without at least encapsulating it. It may be confusing if two verbs (POL and winetricks one) have the same name

**Comment by plata** [comment]
I find that even more confusing if you can directly install the winetricks verb. If you can only open the GUI, the separation would be clearer (at least for me).

**Comment by plata** [comment]
In this case I would rather not support winetricks.

**Comment by madoar** [comment]
I think we're forgetting why people want to have winetricks in their engine tools.
I believe most people don't care whether they use winetricks underneath or our verbs.
The issue in my opinion is, that most people want to use winetricks because it currently is the only way to install "verbs" after a container has been created.

So basically I think we can solve the whole problem by adding a method to install our verbs after a container has been created.

**Comment by t0msk** [comment]
@madoar is right, I use / want to use Winetricks only for installing windows dll's, components and fonts, nothing more and it is only one solution yet.
