### ISSUE TITLE
Cannot install Blizzard app

### ISSUE THREAD

**Issue by t0msk** [PhoenicisOrg/scripts#717]
As you can see on the screenshot I cannot install Blizzard app, on the background of that screenshot is log from console, as you can see there are no errors. I use newest version of Phoenicis from github.

![screenshot_20181205_132412](https://user-images.githubusercontent.com/7276200/49513458-49fc0680-f891-11e8-8672-12cdd9d2e675.png)

**Comment by Zemogiter** [comment]
I've just installed it by using 3.19-staging and removing the `winxp` line since it serves no puporse whatsoever.
