### ISSUE TITLE
Crowdin link on README.md

### ISSUE THREAD

**Issue by ovari** [PhoenicisOrg/scripts#751]
Can a link to the Crowdin be added to the README.md file at:
https://github.com/PhoenicisOrg/scripts/

It probably relates to:
https://github.com/PhoenicisOrg/scripts/tree/master/i18n

It could be similar to the link at:
https://github.com/PhoenicisOrg/phoenicis#translate

What do you think?

Thank you

**Comment by madoar** [comment]
Strictly speaking there is a crowdin badge at the top of the README.
If you click on it you are forwarded to the crowdin page for the scripts.

At the same time I don't see a reason not to add an additional link to the README page, which makes it clear where the translations can be found.

**Comment by ovari** [comment]
Thanks for updating @plata. Should there be another sentence like:

> If your language is not listed, please create an [issue](https://github.com/PhoenicisOrg/scripts/issues).

What do you think?

**Comment by plata** [comment]
Makes sense. Can you create a PR for both repos?

**Comment by ovari** [comment]
https://github.com/PhoenicisOrg/phoenicis/pull/1773
https://github.com/PhoenicisOrg/scripts/pull/817
