### ISSUE TITLE
Including WINEDEBUG="-all" in a script?

### ISSUE THREAD

**Issue by Kreyren** [PhoenicisOrg/scripts#784]
Merge https://github.com/PhoenicisOrg/scripts/pull/783 requires `WINEDEBUG="-all"` in it's installer to improve performance. 

is there a way to include it?

**Comment by ImperatorS79** [comment]
Normally it is the default.

**Comment by Kreyren** [comment]
@ImperatorS79 afaik default is set to include all fixme and errors for DLL and seh. 

Notice the output on https://youtu.be/Spr2jFWmhwU?t=1572

**Comment by Kreyren** [comment]
Game was launched from terminal due bug that prevents game to be added in phoenicis, but creates installation in wineprefix. Closing assuming that WINEDEBUG="-all" is present by default in phoenicis.

**Comment by Kreyren** [comment]
@madoar not relevant to #784, reffer to #787
