### ISSUE TITLE
BUG: Battle.net applications fails on <GAMENAME>.exe

### ISSUE THREAD

**Issue by Kreyren** [PhoenicisOrg/scripts#792]
Battle.net installers fails with unexpected error resulting in installing wineprefix, but not listing it in phoenicis's Library.

### STEPS TO REPRODUCE
Install any battle.net application without `.executable(Battle.net.exe)`. Log-in -> Error occurs prior to log-in.

### WORKAROUND
using `.executable(Battle.net.exe)` fixes the issue, but launches the Battle.net instead of the game -> Expected compatibility issues with end-users installing games on battle.net due missing dependencies in wineprefix that is optimized for other title.

EDIT: same error appears if the Battle.net installer is already installed.

**Comment by ImperatorS79** [comment]
All the Battle.net installers ?

**Comment by Kreyren** [comment]
@ImperatorS79 Correct, testing your hearthstone atm.

**Comment by ImperatorS79** [comment]
@Keyren ok I think the error could come from the fact that you still have prefixes from old tentative of installing those games. Could you go in the containers tab and delete all containers without shortcut ?

**Comment by Kreyren** [comment]
Afaik phoenicis checks if the executable was called for some reason.. That seems like horrible idea for applications that calls external installer/launcher.

Recommends removing this check or adapting a function for extermal launcher/installer if needed.

**Comment by ImperatorS79** [comment]
No, this is just the function that create the shortcut, which is called when the installer ends. But yeah, this does not work is the installer call another .exe to install the game.

**Comment by Kreyren** [comment]
@ImperatorS79 noted.

**Comment by Zemogiter** [comment]
I have no issues with either Battle.net app and Starcraft 2. Check the scripts for both.

**Comment by plata** [comment]
@Zemogiter would you mind taking the lead here and help @Kreyren figuring out why it doesn't work for him?

**Comment by Kreyren** [comment]
@Zemogiter More info? I don't see how is my script different from `star craft II` will test

**Comment by Zemogiter** [comment]
@Kreyren What wine version and what branch (upstream,staging,proton,dos_support,cx) and what architecture (x86 or x64) are you using and what game are you trying to install?

**Comment by Kreyren** [comment]
@Zemogiter How is WINE version relevant since script is using precompiled WINE? Try removing starcraft wineprefix and use battle.net with mobile authentification.

**Comment by plata** [comment]
@Zemogiter @Kreyren what's the state of this issue?

**Comment by Kreyren** [comment]
iirc it's fixed.
