### ISSUE TITLE
BUG: Documentation typo

### ISSUE THREAD

**Issue by Kreyren** [PhoenicisOrg/scripts#805]
On https://phoenicisorg.github.io/scripts/Develop/script-js/#steamscript there is a typo in `.category` variable:
![image](https://user-images.githubusercontent.com/11302521/51073071-b4a81b00-1663-11e9-9252-40a5dfc39c8a.png)

**Comment by Kreyren** [comment]
@plata Created.

**Comment by plata** [comment]
Thanks.

**Comment by Kreyren** [comment]
npnpnpnppnnp
