### ISSUE TITLE
QA: Mono?

### ISSUE THREAD

**Issue by Kreyren** [PhoenicisOrg/scripts#813]
Documentation on https://phoenicisorg.github.io/scripts/Develop/script-js/ lacks info on mono.

How do i use it on phoenicis?

Required for .NET apps

**Comment by ImperatorS79** [comment]
Normally wine will ask for downloading for mono and gecko when creating the prefix.

**Comment by LeandroStanger** [comment]
mono and gecko should be downloaded automatically

**Comment by Kreyren** [comment]
More info? Is MONO already included in all wine builds or ?

Never prompted for anything..

**Comment by Kreyren** [comment]
@plata noted, thanks for info

**Comment by plata** [comment]
Mh. Not quite sure what would be the correct place to document this.

**Comment by Kreyren** [comment]
@plata Maybe make a new tab with info to Engines on https://phoenicisorg.github.io/scripts/Develop/script-js/ ?

**Comment by Kreyren** [comment]
@plata assuming that it affect the compatibility i would say it is alike using mono or using dotnet which is a big difference..
