### ISSUE TITLE
Suggestion: Rename from scripts > Installers

### ISSUE THREAD

**Issue by Kreyren** [PhoenicisOrg/scripts#826]
Suggesting renaming PhoenicisOrg/scripts to PhoenicisOrg/Installers reason beeing that <GITHUB_USER>/script is widely used and may cause conflicts if forked e.i: https://github.com/RXT067/Scripts which is made to workaround this naming and would otherwise be present in my user repository.

Refference : https://github.com/PhoenicisOrg/scripts/pull/815/commits/2896f32007607a47263094c20591c380d685d66a

**Comment by plata** [comment]
We could maybe call it default-repository or something like.

**Comment by Kreyren** [comment]
`default-repository` would be sufficient, but i find it missleading assuming that it contains instructions for phoenicis to install software..

**Comment by madoar** [comment]
I think the name `default-repository` misleading.
Default for what? I'm missing a connection to the scripts.

**Comment by Kreyren** [comment]
@plata elaborate? To me the concept of using zip extractors, downloaders is part of usuall installers?

**Comment by plata** [comment]
It's used by installers, that's correct. However, the downloader itself is not an installer. So strictly speaking, it would not be allowed to be contained in an "installers" repository.

**Comment by Kreyren** [comment]
Just to clarify: i'm saying that using PhoenicisOrg/script is unsane for reasons above. 

We can also approach it creatively and make custom name for it which would also help with passive marketing in theory.

**Comment by plata** [comment]
@qparis @ImperatorS79 @madoar do we want to rename the repository? If not, we should close the issue as "won't fix".

**Comment by qparis** [comment]
I don’t think it will be useful and it might create a lot of confusion over existing installations

**Comment by ImperatorS79** [comment]
I am for the "won't fix".

**Comment by madoar** [comment]
I am also for "won't fix"
