### ISSUE TITLE
Recommendation: make a TEMPLATE/TEMPLATE

### ISSUE THREAD

**Issue by Kreyren** [PhoenicisOrg/scripts#827]
Recommends making a TEMPLATE/TEMPLATE or plugin in sublime text 3 (or other text editors used for contribution) to make a default file hierarchy making the script contribution easier.

_Originally posted by @Kreyren in https://github.com/PhoenicisOrg/scripts/pull/815#commitcomment-31997421_

**Comment by plata** [comment]
I don't think it is possible. There are different types of scripts (Steam/Origin...) and the template cannot know which one you need. The preferred way to go is read the documentation and/or copy an existing script.

**Comment by plata** [comment]
I get your point but can a template do this?

**Comment by Kreyren** [comment]
@plata Based on this conversation i would rather recommend making overengineered script with all posibilities that can be used as an example of a script that we expect from the maintainers to contribute. 

I believe that we can do this assuming that we can make multiple subdirs for Online, Locall, Steam, etc.. but i doubt there is such a software that would fit in all categories afaik skyrim is closest to this requirements, but is not available on uplay nor origin.

**Comment by plata** [comment]
> or in theory can we make customized marking for each script in the repository to provide example that can be sorted based on what the script supports for it's installation?

I don't understand this part.

**Comment by plata** [comment]
We have examples for all types in the script.js documentation already. I don't see how your suggestion would improve anything.

**Comment by Kreyren** [comment]
@plata My expected outcome was to make finding references to make a script more effective. script.js documentation would be sufficient, but it makes it complicated to update making it harder to be self-regulated.

I still think that making a sort functionality to show which script uses which method is helpful, but using documentation is also sufficient.
