### ISSUE TITLE
Request: commit to introduce the tools into a new `CONTRIBUTING.md`.

### ISSUE THREAD

**Issue by Kreyren** [PhoenicisOrg/scripts#828]
Requesting commit to introduce the tools into a new `CONTRIBUTING.md`.

_Originally posted by @Kreyren in https://github.com/PhoenicisOrg/scripts/pull/815#commitcomment-31997424_

**Comment by Kreyren** [comment]
@madoar correct. CONTRIBUTING.md should have instructions to use those tools.

**Comment by plata** [comment]
I really think you misuse the CONTRIBUTING.md. It should contain a link to the tools like we have it now (or maybe a short excerpt how to use them) but nothing over the top. We have everything in the documentation already.

**Comment by Kreyren** [comment]
@plata I see the issue that merging my suggestion would introduce now.

 in theory i could update the `docs/_docs` instead and in CONTRIBUTING.md just basic guidelines for the code that would be displayed in merge request recognized by github functionality would be more sufficient?

**Comment by plata** [comment]
Yep. Like I said in the CONTRIBUTING pull request: keep it simple.

I think we clarified the issue, so I will close this now. Feel free to provide pull requests to improve the documentation if something is not clear.

**Comment by Kreyren** [comment]
Noted
