### ISSUE TITLE
Suggestion: Script Maintainers

### ISSUE THREAD

**Issue by Kreyren** [PhoenicisOrg/scripts#830]
Recommends making Code Of Maintainers and allow recruitment for Script maintainers to maintain entrusted script to make sure that those scripts are working as expected based on feedback -> Team members woudn't be required to maintain scripts.

_Originally posted by @Kreyren in https://github.com/PhoenicisOrg/scripts/pull/815/review_comment/create_

**Comment by plata** [comment]
We do this. We invite people who have been active in the scripts repository to a private chat to ask them if they would like to become a maintainer. For example, we just did so for @ImperatorS79.

**Comment by Kreyren** [comment]
@plata Note that this is a concept that would allow recruitment of multiple contributors and to controll their behavior in a way that is beneficial to a project. 

Your method of resolving it by hand is uneffective assuming that you still have to look for maintainers are not doing something that is not beneficial and if there are conflicts they would have to be resolved the same way.

This is mostly system that is used on huge repositories full of contributors, but i believe that implementation to phoenicis would be also beneficial considering the need to keep the scripts working and updated.

**Comment by plata** [comment]
We will not grant write access to anybody based on some algorithm. If you look at the community which actively collaborates, it is really only a few people. It is very well possible to manage them manually.

**Comment by Kreyren** [comment]
@plata Write access is not expected to be granted to anyone. This is rather expected to make push requests more effective to manage.

> It is very well possible to manage them manually.

Since the linux community lacks working software to manage compatibility layers i would expect the community to grow exponentially assuming that phoenicis would be able to replace lutris and provide scrips working all the time and very effective to update.

I'm aware that currently it's possible to manage manually, but i'm trying to build foundation for contribution to manage scripts.

**Comment by plata** [comment]
How can we make pull requests more effective without having users who can push?

**Comment by Kreyren** [comment]
@plata Inspired by gentoo (for example)

https://github.com/gentoo/gentoo

You can see that merge requests can be only merged as long as they fit into predefined set of rules -> Members woudn't be required to review the code.

**Comment by Kreyren** [comment]
@plata I'm aware of that that's why am i suggesting it. 

Since we can ensure the quality using this set of rules and then make sure to enforce them using those bots + Mensioned set of rules also resolves conflicts and states how the cooperating between maintainers would be made.

**Comment by qparis** [comment]
> You can see that merge requests can be only merged as long as they fit into predefined set of rules -> Members woudn't be required to review the code.

Imagine the consequences in term of security

**Comment by Kreyren** [comment]
@qparis That's the best thing about this approach that the consequences in terms of security are theoretically none since this method only makes it more effective to review the code and avoid confusion.
