### ISSUE TITLE
Suggestion: European Copyright Directive

### ISSUE THREAD

**Issue by Kreyren** [PhoenicisOrg/scripts#831]
Should be reviewed to prepare for New European Copyright Directive.

_Originally posted by @Kreyren in https://github.com/PhoenicisOrg/scripts/pull/815/review_comment/create_

**Comment by Kreyren** [comment]
Sorry didn't realize that github didn't point the issue to the relevant line. 

https://github.com/PhoenicisOrg/scripts/pull/815/commits/2896f32007607a47263094c20591c380d685d66a line +- 53

Recommends using `Signed-off-by: <NAME> <SURNAME> <<EMAIL>>` to transfer the responsibility of used code to contributors if they match EU's copyright master filter. 

This is not permanent fix! should be discussed. Since it may introduce the possibility that contributors would revoke their contribution causing instability in the phoenicis.

**Comment by plata** [comment]
We cannot do this. It will make contributing too difficult for our average user. Apart from this, I believe that the GitHub terms already cover this topic in a sufficient way.

**Comment by Kreyren** [comment]
DISCLAIMER: Based on my understanding:

@plata Note that this is new copyright directive and this is the solution that most of repositories with multiple contributors chosed. 

We are still unsure how the copyright directive would hit linux and this is just a preventive measurements to prevent EU from removing codeblocks from a software since if phoenicis contains copyrighted material (which is defined in master filter and there is a possibility that it may be claimed even if it was made by someone else) that codeblock would be suspended from the repository by github.

**Comment by Kreyren** [comment]
@plata I would still recommend using `Signed-off-by:..` for community merge requests that are commiting directly to the phoenicisorg/phoenicis. I doubt that there would be something with copyright violation in scripts. 

otherwise agree with the approach.

**Comment by plata** [comment]
As GitHub explained recently in a blog post, GitHub is explicitly excluded from the regulation.

**Comment by Kreyren** [comment]
@plata if github operates on EU soil it's not excluded.. source?

**Comment by madoar** [comment]
I think @plata is talking about https://github.blog/2019-02-13-the-eu-copyright-directive-what-happens-from-here/, which links to http://www.europarl.europa.eu/news/en/press-room/20190212IPR26152/agreement-reached-on-digital-copyright-rules.

**Comment by Kreyren** [comment]
Interesting :thinking:
