### ISSUE TITLE
BUG: Phoenicis installer hangs on steam scripts

### ISSUE THREAD

**Issue by Kreyren** [PhoenicisOrg/scripts#834]
### Expected behavior
Me playing StarTrek Online

### Actual behavior
~Me crying over loadi~ If startrek Online is installed on phoenicis it results in loading loop.

### Steps to reproduce
Install StarTrek Online/Assassin's Creed III/Burnout paradise via phoenicis

wait +- 30 mins untill the game is installed depending on the internet connection(?)

![image](https://user-images.githubusercontent.com/11302521/51480513-8926de00-1d91-11e9-9901-25c1529b882b.png)

### Theory

My best bet is that steam didn't start the download on phoenicis trigger? -> Phoenicis is waiting for steam to finish installation that never started to download assuming that steamapps is blank

```
kreyren@dreamon ~/.Phoenicis/containers/wineprefix/Star Trek Online/drive_c/Program Files/Steam/steamapps $ ls
libraryfolders.vdf  sourcemods
```

### Troubleshooting
* Issue is present in recent master https://github.com/PhoenicisOrg/phoenicis/issues/1790#issuecomment-456124433

### System information
* software version - https://github.com/PhoenicisOrg/phoenicis/commit/618e7927ac696a287a8f0fca281acc6d4dfba4ca 
* system-info - https://paste.pound-python.org/show/3hjY50eLStbt878R0hF3/

---

Recommends showing indication of steam installing the game?

**Comment by plata** [comment]
@Kreyren do you still have this issue?

**Comment by Kreyren** [comment]
@plata last time i check i did, may be relevant to https://github.com/ValveSoftware/steam-for-linux/issues/6112

**Comment by plata** [comment]
Issue seem to be related more to a certain OS setup than Phoenicis.

**Comment by Kreyren** [comment]
@plata confirmed beeing relevant to steam.
