### ISSUE TITLE
Abstract: Multiple installers per script

### ISSUE THREAD

**Issue by Kreyren** [PhoenicisOrg/scripts#843]
There are many variables for games to work on WINE -> Something that works for me on Gentoo doesn't have to work on Ubuntu for example due missing libraries, GPU, Kernel Configuration, etc..

Recommending to add multiple installers for each Game (and allow users to vote, leave comments and add labels like 'recommended for gentoo' in GOLD) 

I believe that change alike is mandatory considering that Lutris has simmilar issues -> practically unusable on gentoo, but works OOTB most of the time on ubuntu. 

Installers should also be downloaded on demand from remote server instead of listing repositories due reasons above. 

----

PBA also results in false-trigger on anti-cheat. => Gallium9 is the only way to get better performance atm..

Conclusion: Suspect that staging needs update to allow DXVK/PBA for DirectX11 assuming that it can run DirectX9 game. 

EDIT: PBA on winxp seems to work reaching up to twice as much performance in comparison to Gallium9

EDIT2: i'm also using CSMT

EDIT3: relevant: https://appdb.winehq.org/objectManager.php?sClass=version&iId=36323

EDIT4: Trying:

winecfg
* set windows version to windows xp
* at `libraries` tab add `dnsapi`
* at `staging` tab enable CSMT
* at `Graphics` tab enable `Automatically capture mouse in full-screen windows`

 run wine with these options as environmental variables
* MESA_GLTHREAD=true __GL_THREADED_OPTIMIZATIONS=0

Seems to be performing better in launcher

_Originally posted by @Kreyren in https://github.com/PhoenicisOrg/scripts/pull/797#issuecomment-457430665_

**Comment by plata** [comment]
There's nothing preventing anyone from creating multiple scripts per app. Actually we have that for several (e.g. local and online installation).

**Comment by ImperatorS79** [comment]
For environment variable, this is this issue #213.

**Comment by Kreyren** [comment]
@plata 

I meant allowing multiple scrips for steam for example.

**Comment by plata** [comment]
You can also have multiple scripts for Steam. They just need different names. Some of our scripts currently have e.g. "Steam (Demo)" and "Steam". Honestly, I doubt that we will ever need different script versions for the same application, but it is possible.

**Comment by Kreyren** [comment]
@plata I think that it's not sufficient considering that my suggestion would introduce multiple scripts per one application + user input to decide which script is working the best is mandatory + considering the amount of data per script those should be downloaded on demand. 

We should focus on providing a method to handle the configuration and allowing community to make the configuration best possible making script compatibility should be ignored by upstream. 

Also community such as discord with people willing to share info and educate the contributors is also mandatory.. 


Ideally we would have something like a script name and author of that script with votes and comments in phoenicis gui. I believe that it's the most effective way to make all scripts working on phoenicis on all OS and variables.

**Comment by plata** [comment]
Multiple scripts have the problem that script 1 might have issue a and script 2 issue b leading to two scripts which do not fully work. Therefore, it's much better to have one script which is continuously improved by pull requests and reported issues. Also, this approach provides much more information about the problems of a script than just a rating.

**Comment by Kreyren** [comment]
> Therefore, it's much better to have one script which is continuously improved by pull requests and reported issues. 

Disagree that is how lutris works and most scripts are not working.. but agree with closing now, we can reopen when this problem appears..

**Comment by madoar** [comment]
@Kreyren why isn't this process working?
I mean if a script doesn't work why write a new one when you could simply fix/rewrite the existing one?

**Comment by Kreyren** [comment]
@madoar Since it encourages ppl to make their own script it it's not working for them and interact with phoenicis community for support.. Example AUR or Gentoo-overlays Instead of having one thing that is controlled by upstream and limits the community.. -> Self-maintainance, self-QA and more working scripts.

**Comment by qparis** [comment]
> @madoar Since it encourages ppl to make their own script it it's not working for them and interact with phoenicis community for support.. Example AUR or Gentoo-overlays Instead of having one thing that is controlled by upstream and limits the community.. -> Self-maintainance, self-QA and more working scripts.

And also more non-working scripts. Imagine you are looking for a blue ball inside a bag that contains 1000 hundred red balls and 10 blue balls. You pick 10 balls randomly and you conclude that all the balls are red. This is exactly what is happening with POLv4 scripts and this is exactly what is going to happen if you demultiply the number of scripts like you suggest.

The decision has been taken, I suggest we move on to other ideas

**Comment by Kreyren** [comment]
> And also more non-working scripts. I

it doesn't... thats the point of it.. it make more working scripts..

> Imagine you are looking for a blue ball inside a bag that contains 1000 hundred red balls and 10 blue balls. You pick 10 balls randomly and you conclude that all the balls are red. 

Thats why filters like Gentoo, Debian, AMD, nvidia are mandatory.. we can also pick features script that we verified works so that end-user doesn't have to search..

> This is exactly what is happening with POLv4 scripts and this is exactly what is going to happen if you demultiply the number of scripts like you suggest.

This is no where near POLv4 scripts.. POLv4 was already explained multiple times why is it's approach futile..

**Comment by qparis** [comment]
Talking about explaining things many time, I really think that you should listen and trust a little more what we are trying to explain based on our experience (no offense, but I think we (i.e. the whole team that agree on this point) have more hindsight). I have the impression that we've be talking for hours about it and you keep trying to reintroduce the idea at different places. 

Even if you think that it "nowhere near POLv4 scripts", POLv4 teaches us a lot about contributor behavior whether you like it or not. 

So, once last time: 
* People often contribute once and only once. Rare are those who come back to maintain their scripts. Once they do no longer need app or they have finished their game, people generally do not update their own script. 
* Scripts do not break one by one in general. Most of the time, many script break at the exact same time (wine upgrade, distribution upgrade, etc...). 
* 3 script doing the same stuff = 3 script to repair once a regression is found. Whether you like it or not, even if it is not done by the same person. 
* Just do the maths. The number of scripts required will be exponential (literally, not just a way of speaking!) to the number of parameters. 50 distro  * 3 graphic cards  * ~3 installation medium * 1000 apps ~= 450 000 scripts. No way this is substainable. Even if your model is more scalable (which remains to be proven because the current contribution system allows people to work in parallel), it will never compensate an exponentially growing number of scripts. 
* Updating a guide and updating a script does not require the same skill, neither the same motivation. You cannot compare

==> I can guarantee you that with this model, you'll end-up with a majority of non working script. And when its happen, people will tell that the platform is garbadge. That's it.

**Comment by Kreyren** [comment]
>  I really think that you should listen and trust a little more what we are trying to explain based on our experience (no offense, but I think we (i.e. the whole team that agree on this point) have more hindsight). I have the impression that we've be talking for hours about it and you keep trying to reintroduce the idea at different places.

I've agreed with closing for now, tried to explain my reasoning based on provided references and my experience since I suspect that this issue would have to be re-open in the future..

Your decision is respected and you have final word..

> POLv4 teaches us a lot about contributor behavior whether you like it or not.

My reasoning is also based on experience from POLv4 from different point of view..

> People often contribute once and only once. 

This depends on the implementation of the contribution.. People are gladly going to contributibute more if you make it effective for said abstract..

>  Rare are those who come back to maintain their scripts. Once they do no longer need app or they have finished their game, people generally do not update their own script.

> Scripts do not break one by one in general. Most of the time, many script break at the exact same time (wine upgrade, distribution upgrade, etc...).

> 3 script doing the same stuff = 3 script to repair once a regression is found. Whether you like it or not, even if it is not done by the same person.

Agreed thats why i suggest rating, user input in comments and community interaction so that those scripts can be forked, etc..

> Just do the maths. The number of scripts required will be exponential (literally, not just a way of speaking!) to the number of parameters. 50 distro * 3 graphic cards * ~3 installation medium * 1000 apps ~= 450 000 scripts. No way this is substainable. Even if your model is more scalable (which remains to be proven because the current contribution system allows people to work in parallel), it will never compensate an exponentially growing number of scripts.

My model is scaleble and counts with this maintainance look on AUR or DotA 2 guides for references..

I belive that your current model can never maintain all scripts at once and to ensure their quality.

> Updating a guide and updating a script does not require the same skill, neither the same motivation. You cannot compare

It does.. make a community around it and provide support so that people are motivated to maintain the scripts, learn, QA each other and help each other -> You have solved problem with script maintainance and phoenicis can focus only on phoenicis development and totally ignore scripts excluding providing maintannce and portal to maintain wiki.

Which is problem on lutris atm, afaik lutris was previously made to work on simmilar model, but their documentation is unusable, script maintainers are not encouraged and lutris's core is horrible because it's written as project by a developer with minimal experience in python (or so i was told..) + bugs are ignored, etc.. etc..

> ==> I can guarantee you that with this model, you'll end-up with a majority of non working script. And when its happen, people will tell that the platform is garbadge. That's it.

I can guarantee you that as well since it's expected there will be a lots of scripts that are not working using this model but assuming that:
- Wiki is provided and maintained
- Discord is provided with phoenicis team to educate community and interact with them to ensure that they understand how to write scripts correctly
- Bugs are not ignored
- Core functionality is maintained and is not full of bugs like:
https://github.com/lutris/lutris/issues/1825
https://github.com/lutris/lutris/issues/1167
- Code of conduct based on anarchy developement process or simmilar that can be community maintained is provided
- OSS bot to check sanity of provided scripts or a method so that script maintainers can submit it without phoenicis review
- etc.. depending on the implementation

**Comment by Kreyren** [comment]
but agree that it's sane to approach with your method for now, this can be implemented any time..
