### ISSUE TITLE
Warning about installation id during FAudio installation

### ISSUE THREAD

**Issue by madoar** [PhoenicisOrg/scripts#848]
When installing FAudio through the verbs tab in the containers view I see the following warning:

```
[WARN ] org.phoenicis.javafx.views.mainwindow.installations.dto.InstallationDTO (l.53) - Installation ID (FAudio_1548949063211) contains invalid characters, will remove them.
```

**Comment by plata** [comment]
Can you check the allowed characters? Maybe it removes the `_`. Probably this should happen with every installation though.

**Comment by plata** [comment]
@Zemogiter I don't think so. Should happen for everybody then.

**Comment by ImperatorS79** [comment]
From my experience this warning is always displayed.

**Comment by plata** [comment]
@ImperatorS79 yes, but the error @Zemogiter does not happen for others (afaik).

**Comment by ImperatorS79** [comment]
So the error, which is #844, is not related to this issue, which does not seem to be one.

**Comment by plata** [comment]
That's how I would see it currently, yes.

**Comment by plata** [comment]
@madoar I think this is fixed. Can you confirm?

**Comment by plata** [comment]
Closed due to inactivity. @madoar if you still have the issue, feel free to re-open.
