### ISSUE TITLE
Script (under Test): Elite Dangerous + Steam

### ISSUE THREAD

**Issue by suamor** [PhoenicisOrg/scripts#858]
I'm trying out the script to install EliteDangerous. Unfortunately I'm stuck in the Steam Installation step. 
Up to this step the installation seemed to work fine (wine 4.0 staging, .Net 4.5.2, DX10 and other dependencies installed, not sure why staging was used as stable is released since a longer time).

I have Elite Dangerous from Frontier Store. It is a quite common way to get Elite Dangerous.
Steam should be one of two options (select Installer Package or Download from Steam).

Also it would be great to know how to proceed from here (apart from looking into the script itself). 

System: Ubuntu 18.04 (with all updates installed).
Phonicis: SnapShot just downloaded and installed.

**Comment by Zemogiter** [comment]
Just tested it and I got errors at `dotnet452` installation. The same I had in https://github.com/PhoenicisOrg/scripts/pull/840#issuecomment-460845318
Steam installed fine though.

**Comment by suamor** [comment]
Yes, I have the same here. The Prefix was updated to 4.0 .
Steam works fine, I can install the ED Launcher too, but not start because .Net is broken.

Installing 4.0 via "Verbs" or any later versions fails, independently if wine-mono was installed previously or not. One of the scripts fails on this check and may crash or whatever (no log). 

I have not tried anything else than win10 as configuration option.

**Comment by ImperatorS79** [comment]
> "mscorlib recursive resource lookup" and "Infinite recursion during resource lookup..." Resource Name: Arg_ExternalException.

Generally this is the sign of a broken .NET instalation.

> Up to this step the installation seemed to work fine (wine 4.0 staging, .Net 4.5.2, DX10 and other dependencies installed, not sure why staging was used as stable is released since a longer time).

You should not use the dx10 verb here, it is far better to use DXVK.

**Comment by suamor** [comment]
Ok, then I will better try do a completely manual installation so I have a better control and understanding of the individual steps.

I found myself out that 4.5.2 is likely broken, because some winecfg entry  had not been set as described here for newer .Net installation including 4.5.2:
https://appdb.winehq.org/objectManager.php?sClass=version&iId=34219

The original 4.5.2 page states that additionally some registry entries need to be set manually. Not sure if this step is still required as it was not mentioned on the other page.

**Comment by ImperatorS79** [comment]
Yes, I just tested it in winetricks and dotnet452 fails also. Maybe try with just dotnet40 or dotnet45. Those verbs (dotnet) seems really broken, even in winetricks :/

**Comment by Zemogiter** [comment]
Tried installing dotnet472 on Space Engineers prefix via Verbs tab and didn't get any errors.

**Comment by suamor** [comment]
Simply installed 461 without 452 (manually with /q option) and afterwards I could run EDLaunch (but login gives me graphical error, will have to check logs tomorrow). Also you may need to install libjpeg62.

**Comment by ImperatorS79** [comment]
@suamor when I launch dotnet461, it simply fails...

**Comment by suamor** [comment]
What I did after using verbs dotnet40:
1) open shell (terminal button, engine tools)
2) winecfg -> set to windows-7 (and check mscoree is set to "native")
3) $ wine64 /path/to/elite/installer (exe)
4) $ wine64 ../../resources/NDP461-KB3102436-x86-x64-AllOS-ENU.exe /q
5) $ cd <prefix-name>/drive_c/Program\ Files\ \(x86\)/Frontier/EDLaunch/
6) $ wine64 edlaunch.exe

Also I was able to start synching as the graphics sometimes seems to get stable...

**Comment by ImperatorS79** [comment]
Well, doing this NDP just output 5 fixme's and then nothing on my side...

**Comment by suamor** [comment]
For a different game I wanted to try out with wine I even was able to install 452 using the resource file. The rest similar as above.

What I was unable to do is to get it working without installing dotnet40 before (in xp mode after having removed wine-mono). I have now edited above steps to make it more clear.

**Comment by plata** [comment]
Is this discussion still about Elite Dangerous or is it now above dotnet problems in general? If so, we should change the title.

**Comment by suamor** [comment]
Well for me it is that somebody should fix everything so Elite can be installed and played using phoenicis. We could however create sub-issues for each script that may need to be adjusted.

**Comment by ImperatorS79** [comment]
@suamor I still do not manage to install dotnet461, it just fails after 3 seconds. So I wonder how it works on your computer :thinking: .

**Comment by suamor** [comment]
No idea.. just in case, this is my 461:
$ ls -alh ../../resources/NDP461-KB3102436-x86-x64-AllOS-ENU.exe 
-rw-rw-r-- 1 <user> <group> 65M Feb  7 17:51 ../../resources/NDP461-KB3102436-x86-x64-AllOS-ENU.exe

**Comment by ImperatorS79** [comment]
Same... Really strange.

**Comment by ImperatorS79** [comment]
In phoenicis verbs or in winetricks, the os version is modified multiple times to avoid this.

**Comment by suamor** [comment]
Hmm.. I can only tell you that I cannot install it with verbs (which should be the same as winetricks). However I'm not sure if I tried verbs 461 without dotnet40 being installed.

**Comment by ImperatorS79** [comment]
@suamor Please tell us if this is fixed with latest git.

**Comment by plata** [comment]
Closed due to inactivity. @suamor please re-open if you have any news.
