### ISSUE TITLE
Installing apps on Mac fails 'Cannot read property "toString" from undefined in [utils, functions, net, download]'

### ISSUE THREAD

**Issue by hagabaka** [PhoenicisOrg/scripts#860]
When I try to install any on Phoenicis 0.5-alpha on Mac, I get an error
```
TypeError: Cannot read property "toString" from undefined in [utils, functions, net, download] at line number 149
```
I think this comes from [here](https://github.com/PhoenicisOrg/scripts/blob/master/Utils/Functions/Net/Download/script.js#L148), so apparently `downloadFile`, returned by `this._downloader.get` is undefined.

When I try to call the `get` function from the Phoenicis console, for example `Bean('downloader').get('https://www.7-zip.org/a/7z1801.exe', '/Users/ychen/Library/Phoenicis/tmp/test', {}, function(progress) {})`, it returns `null`.

If I replace the line causing the error with
```
return this._localDestination;
```
The installation continues without the error.

**Comment by suamor** [comment]
This is a generic error message from java not showing the real issue. Look further into the log file or upload the whole one so it can be examined.

I had two different issue with this message, one was that openjdk11 was not installed (on Ubuntu 18.04 the opendjk10 is advertised as 11... without even offering the real one).

**Comment by qparis** [comment]
It seems that your version of Phoenicis (probably alpha 2) does not match with your repository
