### ISSUE TITLE
Prevent admins from directly pushing into master branch. 

### ISSUE THREAD

**Issue by qparis** [PhoenicisOrg/scripts#863]
I realized tonight that when upstream is set to my .git/config file, I can push to it without any warning. 
I reverted the changes I mistakely made but it would be cool if the protection prevented us from pushing into upstream.

**Comment by plata** [comment]
As far as I know, this is not possible.

**Comment by Kreyren** [comment]
afaik github has "teams" that has this function so that you can limit access to the repositories.

**Comment by plata** [comment]
@Kreyren any admin rights will overrule team restrictions.

**Comment by Kreyren** [comment]
@plata I see.. recommends contacting github about it they might have some solution to it.

**Comment by plata** [comment]
@qparis I would suggest do close this because I do not see any possibility to solve the problem. Do you agree?

**Comment by qparis** [comment]
Yep
