### ISSUE TITLE
Problem: EasyAntiCheat

### ISSUE THREAD

**Issue by Kreyren** [PhoenicisOrg/scripts#866]
Currently games that uses EasyAntiCheat are problematic on linux alike:
- Apex Legends
- SMITE
- Paladins

Is there something we can do about this in phoenicis?

### Developer might be trying to block WINE

Game worked on it's release day https://youtu.be/OxDHi5aAwSk , but now results in EAC error which is fatal.

Based on previous experience with League Of Legends (https://www.reddit.com/r/leagueoflinux/comments/904ofh/new_patch_new_problems_for_wine_users/) it's possible that developer is trying to prevent usage of WINE on it's games. Reason usually is that it's practically impossible to make a working anti-cheat for linux due it's  

From video https://www.youtube.com/watch?v=W7MC05_JN68&list=PLhixgUqwRTjzzBeFSHXrw9DnQtssdAwgG&index=5 you can see how far can you get just by using **ONE VARIABLE** in linux.. 

From forum post https://forum.winehq.org/viewtopic.php?f=8&t=30553 Bobwya stated that developers of Dead by Daylight are actively trying to blacklist WINE. (Unconfirmed?)

Relevant WINEBUG: https://bugs.winehq.org/show_bug.cgi?id=44235

### RUMOR: Valve is working on compatibility for EAC on linux?

https://www.gamingonlinux.com/articles/apparently-valve-are-working-with-easy-anti-cheat-to-get-support-in-steam-play.13573

## Possible fix

Assuming that game works on Windows maybe we can make WINE undetectable by EAC and fix fixme that are affecting it's function?

## Relevant
https://allthings.how/apex-legends-update-linux-error-eac-sandbox-not-active/
https://www.reddit.com/r/wine_gaming/comments/aqeyf1/currently_playing_apex_legends_on_linux/
https://www.reddit.com/r/linux_gaming/comments/ao3au6/some_interesting_notes_about_eac_error_in_apex/

**Comment by plata** [comment]
Is this anything we have to consider? Sounds more like a Wine issue to me.

**Comment by Kreyren** [comment]
@plata WINE is unable to handle windows kernel atm which is what is causing issues even when EAC offers Linux kernel compatibility based on available info. I understand that some game developers are actively trying to block linux from their games this way.

Based on https://www.gamingonlinux.com/articles/apparently-valve-are-working-with-easy-anti-cheat-to-get-support-in-steam-play.13573 it was confirmed that Valve is working on a fix which would mean that we would have to make a verb for it most likely or do you have other option?

**Comment by Zemogiter** [comment]
I remember that in Wine Staging there was a setting in the "Staging" tab that is called "Hide wine version from apps" or something similiar.

**Comment by Kreyren** [comment]
@Zemogiter Not sufficient, EasyAntiCheat is able to detect wine even when that option is selected afaik

**Comment by plata** [comment]
> Valve is working on a fix which would mean that we would have to make a verb

Depends on what the fix will be. Maybe they change something in Wine internally. So unless we don't know what exactly must be done, there's nothing we could do.
