### ISSUE TITLE
Run Wine app with custom environment variables

### ISSUE THREAD

**Issue by Kreyren** [PhoenicisOrg/scripts#869]
How do i make script to invoke `DXVK_CACHE=PATH wine` in phoenicis?

Reference: https://github.com/PhoenicisOrg/scripts/pull/795#partial-pull-merging

**Comment by ImperatorS79** [comment]
Duplicate of #213.

**Comment by plata** [comment]
This must be added as a new parameter for `engine#run()`, see: https://github.com/PhoenicisOrg/scripts/blob/a6bbe8d1d65278995dcf483ec8a33e7ab3127785/Engines/Wine/Engine/Implementation/script.js#L236

**Comment by Kreyren** [comment]
:thinking: 

if already present example usage?

**Comment by plata** [comment]
Just check where `Wine.run` is called.
