### ISSUE TITLE
League of Legends link dead

### ISSUE THREAD

**Issue by rowbawts** [PhoenicisOrg/scripts#870]
When you try to install the League script fails on the initial download of the installer because the link is old see [here](https://riotgamespatcher-a.akamaihd.net/ShellInstaller/NA/LeagueofLegends_NA_Installer_2016_05_13.exe)

**Comment by plata** [comment]
Do you know what the link should be?

**Comment by madoar** [comment]
This issues is likely linked to #797.

**Comment by rowbawts** [comment]
Seems like it, but the links in the PR also have the same error.

**Comment by Kreyren** [comment]
League Of Legends in not working in Phoenicis atm due https://github.com/PhoenicisOrg/scripts/issues/841

Once that is fixed we can make a merge request, working on DXVK support atm.

**Comment by Kreyren** [comment]
Is noted, recommends closing the issue.

**Comment by Kreyren** [comment]
Duplicate of https://github.com/PhoenicisOrg/scripts/issues/777

**Comment by plata** [comment]
To be tracked in #797.
