### ISSUE TITLE
NWN2: Case study

### ISSUE THREAD

**Issue by SanZamoyski** [PhoenicisOrg/scripts#879]
### Expected behavior
Installing and playing the game ;)

### Actual behavior
Game installs (manual) but makes no shortcut. 
Unable to make shortcut manualy (in Library), does nothing. Hitting create gives no response, no info in terminal. 
Running game is bit tricky: running from Containers -> Tools -> Run executable, gives crash with no useful information. BUT! Running through engine tools -> Command prompt -> dir to directory -> nwn2.exe runs the game.

### Steps to reproduce
I have original Polish DVD version, copied that on external drive (i have no CD-ROM on my system) and run installation from.

### System information
* Version 5.0-alpha-2, GIT revision ends with badce66c (2018.12.31)
* Linux Mint KDE, Linux lati 4.15.5-041505-generic #201802221031 SMP Thu Feb 22 15:32:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux, 18.sth.
* san@lati ~ $ java -version
openjdk version "1.8.0_191"
OpenJDK Runtime Environment (build 1.8.0_191-8u191-b12-0ubuntu0.16.04.1-b12)
OpenJDK 64-Bit Server VM (build 25.191-b12, mixed mode)

I know, that this is more than one issue, but i'm not sure where to start...

Also, running Local install takes ages to "download wine?os=linux", why is that? (it starts very slowly)

**Comment by plata** [comment]
Closed due to inactivity. @SanZamoyski feel free to re-open if you have any new findings.
