### ISSUE TITLE
Notepad++ doesn't run with Wine 4.0

### ISSUE THREAD

**Issue by plata** [PhoenicisOrg/scripts#884]
![error](https://user-images.githubusercontent.com/3973260/53822287-c1fcca00-3f6f-11e9-9e9d-afda3214a767.png)

It works e.g. with Wine 3.0. I'm not completely sure if this is a Phoenicis or Wine issue (it happens as well when I run Wine from command line but it could still be a winebuild problem).

**Comment by Zemogiter** [comment]
Reports say wine 4.2 works.

**Comment by madoar** [comment]
I can't reproduce this. I've installed Notepad++ with Wine 4.0 and I can start it afterwards.

**Comment by plata** [comment]
Than it's maybe a missing library. I'm on Manjaro.

**Comment by Zemogiter** [comment]
I also can't reproduce. Notepad++ works.

**Comment by plata** [comment]
Will re-open if I experience the issue again.
