### ISSUE TITLE
Abstract: Merge Requests with Research

### ISSUE THREAD

**Issue by Kreyren** [PhoenicisOrg/scripts#885]
Recommends supporting markdown file with research in scripts that are using WINE engine with research.

### Reasoning
- Research for a one game takes a lots of time to ensure quality and compatibility.
- Would allow more effective maintainance for script maintainers since it would provide point of reference to see that configuration A had issues on OS B cause of WINE missing C, etc..

In theory this could be a section on a wiki to which community can contribute with data..

**Comment by plata** [comment]
> Recommends supporting markdown file with research in scripts that are using WINE engine with research.
Sorry, I don't understand what you propose.

**Comment by Kreyren** [comment]
@plata Something alike https://github.com/RXT067/Research/tree/master/WINE-Dishonored2

To help script maintainers with script development. 

Simmilar to https://github.com/PhoenicisOrg/scripts/pull/877

**Comment by plata** [comment]
Isn't that basically the information which is available in WineHQ app DB?

**Comment by Kreyren** [comment]
@plata depends, WineHQ is not reliable since it's spammed with ppl that doesn't know what are they doing.

But WineHQ would be sufficient if relevant. -> Encourate contributors to file WineHQ before making the installer?

**Comment by plata** [comment]
At least that's what I do normally. It also has the advantage that other people can profit from your findings.

**Comment by Kreyren** [comment]
Fair enough
