### ISSUE TITLE
BUG(?): Seems to hang (+- 5 min) when wine 4.1 is already installed.

### ISSUE THREAD

**Issue by Kreyren** [PhoenicisOrg/scripts#891]
Seems to hang when wine 4.1 is already installed.
![image](https://user-images.githubusercontent.com/11302521/53994175-d8528380-4131-11e9-9762-6496dfe72a5c.png)

_Originally posted by @Kreyren in https://github.com/PhoenicisOrg/scripts/pull/797#issuecomment-470726239_

Reproducable: on random

Steps to reproduce:
- Install wine 4.1 in phoenicis
- install game that utilizes wine 4.1

Since it's reproducable on random recommends ignoring the bug and wait for additional feedback.

**Comment by plata** [comment]
Sounds like a known issue. @qparis was suspecting that it's an issue with the thread pool.

**Comment by plata** [comment]
Like stated above, we are tracking this issue already. Therefore closed as duplicate.

**Comment by Kreyren** [comment]
@plata reference it.

**Comment by plata** [comment]
https://github.com/PhoenicisOrg/phoenicis/issues/1807
