### ISSUE TITLE
QA: OSU! installer is outdated by default

### ISSUE THREAD

**Issue by Kreyren** [PhoenicisOrg/scripts#893]
Flatpaked alpha_2 of phoenicis installs outdated repository -> Force repository refresh on first launch.

Actuall result: 
![image](https://user-images.githubusercontent.com/11302521/54290225-e7f71f80-45aa-11e9-94cd-d972fc1939da.png)

Note that new installer uses wine and installs OSU! from source.

Seems to download from wrong repo
![image](https://user-images.githubusercontent.com/11302521/54292015-bfbcf000-45ad-11e9-8a16-35411da2f11c.png)

Results in on master repository
![image](https://user-images.githubusercontent.com/11302521/54292356-57bad980-45ae-11e9-8710-1c7a101fb8c7.png)

If fix is not possible -> Force OSU! in testing on beta_2 branch

System info:
![image](https://user-images.githubusercontent.com/11302521/54290240-ef1e2d80-45aa-11e9-9ec8-22582aeabdfb.png)
Fedora

Reported by community member, filed by me.

**Comment by plata** [comment]
Looks to me like the software doesn't match with the scripts repo. So update both and try again.

**Comment by Kreyren** [comment]
@plata Updating on master is not always an option on those distros, but that can't be fixed since alpha2 lacks features it seems.

**Comment by plata** [comment]
You have two choices:
- Use a certain release (like alpha 2) and live with what's available there.
- Use the latest and greatest master. In this case, you have to ensure that your scripts and software match.
