### ISSUE TITLE
Use autogenerated function documentation

### ISSUE THREAD

**Issue by plata** [PhoenicisOrg/scripts#9]
The function documentation should be automatically generated from the comments in javascript.

How this could be done with Jenkins: http://blog.cgdecker.com/2011/02/deploying-documentation-to-github-pages.html

And for Travis: https://gist.github.com/vidavidorra/548ffbcdae99d752da02 or https://docs.travis-ci.com/user/deployment/pages/

**Comment by plata** [comment]
We could also use [sphinx-js](https://github.com/erikrose/sphinx-js) and [ReadTheDocs](https://readthedocs.org/). There's a description in the [example](https://github.com/erikrose/sphinx-js#example).

What do you think?

**Comment by plata** [comment]
If we use GitHub pages instead of the wiki for documentation, we should generate the jsdoc to a subfolder (e.g. `docs/jsdoc`) and then include this as a link or with Jekyll `include`.

**Comment by madoar** [comment]
Yes, I agree

**Comment by plata** [comment]
To generate, execute:
```
jsdoc -d docs/jsdoc -r .
```
