### ISSUE TITLE
REQUEST: Replace `* Installer` with Master Installer.

### ISSUE THREAD

**Issue by Kreyren** [PhoenicisOrg/scripts#906]
Requesting removal of all present Installers and replace them with one Master Installer to rule them all.

### ABSTRACT
Make writing installers obsolete -> Avoids end-user script syntax errors and make script maintainance faster.

**Comment by plata** [comment]
How is that supposed to work?

**Comment by Kreyren** [comment]
@plata Ideally built-in feature that makes new container and opens a menu that allows interactions with said container like:

Installing/removing workarounds, installing programs (invoking wine like `phoenicis-wine container pathname` -- AND -- via GUI) and everything needed to make a new script with export ideally -> making writing scripts manually obsolete -> Allowing better maintainance of scripts and contribution.

**Comment by plata** [comment]
That's basically Online/LocalInstallerScript.

**Comment by Kreyren** [comment]
yep, but those are not sufficient nor usable + i see no reason to differenciate them..

**Comment by plata** [comment]
Can you list what exactly you are missing? We have an open issue to add support for verb installation already. Anything apart from that?

**Comment by Kreyren** [comment]
@plata reference the issue, i don't know what you mean.

**Comment by plata** [comment]
https://github.com/PhoenicisOrg/scripts/issues/836

**Comment by plata** [comment]
Closed due to inactivity.

**Comment by Kreyren** [comment]
Fair enough, working on something with low_priority
