### ISSUE TITLE
Request: add msxml6 verb

### ISSUE THREAD

**Issue by Kreyren** [PhoenicisOrg/scripts#910]
Requesting `msxml6` verb that is required for https://github.com/PhoenicisOrg/scripts/pull/908

**Comment by plata** [comment]
See:
https://github.com/Winetricks/winetricks/blob/7b4e62d481f631452b0f19f0209e48541ebc1f4b/src/winetricks#L9828

**Comment by ImperatorS79** [comment]
Fixed by #922
