### ISSUE TITLE
Request: Add atmlib verb

### ISSUE THREAD

**Issue by Kreyren** [PhoenicisOrg/scripts#911]
Requesting atmlib verb that is required for https://github.com/PhoenicisOrg/scripts/pull/908

**Comment by plata** [comment]
What is this? I cannot find it in winetricks nor in PoL 4.

**Comment by plata** [comment]
Or did you mean "atmlib"?

**Comment by plata** [comment]
In this case, it would be a simple cabextract call:
https://github.com/Winetricks/winetricks/blob/7b4e62d481f631452b0f19f0209e48541ebc1f4b/src/winetricks#L5746

**Comment by qparis** [comment]
AFAIK amtlib is the library that is overwritten when Adobe is cracked. After some research, Adobe CC 2019 does no longer use it.

**Comment by plata** [comment]
Mh. [WineHQ](https://appdb.winehq.org/objectManager.php?sClass=version&iId=37541) mentions atmlib.

**Comment by Kreyren** [comment]
`atmlib` correct, my bad, updated

**Comment by ImperatorS79** [comment]
Fixed by #923.
