### ISSUE TITLE
Abstract: improve sort order in phoenicis

### ISSUE THREAD

**Issue by Kreyren** [PhoenicisOrg/scripts#913]
This is not how we organized the scripts. We should have one different script per version.

_Originally posted by @qparis in https://github.com/PhoenicisOrg/scripts/pull/908#issuecomment-485069211_

---

Seems wastefull assuming that this can be done in one folder instead of making multiples that would spam.

**Comment by qparis** [comment]
Description and title of this issue is not clear enough

**Comment by Kreyren** [comment]
@qparis updated, rm your comment and i will remove mine for clarity if sufficient.

OP will be updated with more info if needed.

**Comment by plata** [comment]
Honestly, I still don't understand what this issue is all about.

**Comment by Kreyren** [comment]
@plata updated OP, better?

**Comment by qparis** [comment]
Honestly we don't want to go in this direction. We don't want to support every single version of every program either.
We only may want to support the major versions at the same time, and it does not justify to create an additional level of script hierarchy

**Comment by Kreyren** [comment]
@qparis disagree, lots of user might want to use different version of said software and said support is painless for phoenicis assuming that scripts would be community maintained -> More options more opportunities to contrib and enhance phoenicis functionality.

**Comment by plata** [comment]
For free software, I agree to @qparis. It doesn't make sense to maintain old software forever. However, I can also understand that this might be different for software where you can only use a certain version (e.g. because you bought it). In any case, there is no alternative to providing one script per version simply because the versions might need different Wine versions, settings, verbs etc. So, @Kreyren I get your point but it's not possible technically.

**Comment by Kreyren** [comment]
>  get your point but it's not possible technically.

that's literally what wine is doing on WineHQ -> very possible and usefull for FOSS software as well..

**Comment by plata** [comment]
I don't see how Wine provides scripts. If you refer to the test reports, this is handled exactly like we do it.

**Comment by Kreyren** [comment]
@plata i meant the instructions to make wineapp working on linux is the same as proposed with same reasons.

**Comment by plata** [comment]
Sorry, but that's just not true in general. Of course, there might be apps where this is the case but you cannot assume that it's always like this and therefore it is nothing Phoenicis could rely on.

**Comment by Kreyren** [comment]
it's not expected to be relied on it's expected to be compatible only.

**Comment by plata** [comment]
I don't see how this could work in a general way. If you want to implement the behavior for a certain app, do it like this: Add a `preInstall` step with a choice wizard where the user can select the version.

**Comment by Kreyren** [comment]
@plata also possibility

**Comment by plata** [comment]
Why?

**Comment by Kreyren** [comment]
> Why?

Cause of different methods to handle the wineapps so you would have to have complex non-standart configuration of those scripts + phoenicis has this function already..

**Comment by plata** [comment]
Using one script for multiple versions is non-standard anyways (because of the reasons I've listed above). If we add this very special case to the quick scripts, the quick scripts will become more complicated for the average case which kind of defeats your point.

**Comment by Kreyren** [comment]
@plata yes but we are not using one script for multiple versions we are using one script folder for multiple versions

>  If we add this very special case to the quick scripts, the quick scripts will become more complicated for the average case which kind of defeats your point.

or you make two standarts for these two usecases like everyone else in linux..
