### ISSUE TITLE
Wine: install runtime

### ISSUE THREAD

**Issue by plata** [PhoenicisOrg/scripts#930]
Install the Wine runtime during Wine installation.

Place to implement: https://github.com/PhoenicisOrg/scripts/blob/d4b9ff5da52321728122ea2f38c50aee18da68fc/Engines/Wine/Engine/Implementation/script.js#L35
It can be done similar to gecko/mono:
https://github.com/PhoenicisOrg/scripts/blob/d4b9ff5da52321728122ea2f38c50aee18da68fc/Engines/Wine/Engine/Implementation/script.js#L101
Runtime must be added to `LD_LIBRARY_PATH`: https://github.com/PhoenicisOrg/scripts/blob/d4b9ff5da52321728122ea2f38c50aee18da68fc/Engines/Wine/Engine/Implementation/script.js#L260

see also:
- https://github.com/PhoenicisOrg/phoenicis-winebuild/issues/62
- https://github.com/PhoenicisOrg/phoenicis/issues/1940

**Comment by Kreyren** [comment]
![](https://media.giphy.com/media/xKZ8WistIACmMQw2Nd/giphy.gif)

**Comment by plata** [comment]
Is the description clear enough for everybody or do you need more detailed information?

**Comment by Kreyren** [comment]
Building custom sandbox for a friend that can't get wine on his system, any ETA?

**Comment by plata** [comment]
Not really, why don't you give it a try?

**Comment by Kreyren** [comment]
@plata Trying in sandbox with phoenicis wine, probably not relevant
![image](https://user-images.githubusercontent.com/11302521/57567634-8d2c4980-73dc-11e9-815b-e76d791bc5be.png)

**Comment by ImperatorS79** [comment]
A "pseudo-code" for this:
```
instalRuntime()
{
        download_runtime_json();
        if(!runtimeDir)
        {
		download_runtime();
		extract_runtime();
		storeChecksum();
        }
	else
	{
		differentCheckSum = compareJson();
		if(differentCheckSum)
		{
			removePreviousRuntime();
			download_runtime();
			extract_runtime();
                        storeChecksum();
		}
	}
}
```

**Comment by Kreyren** [comment]
hurray!
1[](https://media.giphy.com/media/rVbAzUUSUC6dO/giphy.gif)
