### ISSUE TITLE
REQUEST: Disable UseTakeFocus on demand

### ISSUE THREAD

**Issue by Kreyren** [PhoenicisOrg/scripts#936]
Based on https://github.com/PhoenicisOrg/scripts/issues/934 :

```
Affected by https://bugs.winehq.org/show_bug.cgi?id=45937

Hotfix is to disable UseTakeFocus in HKEY_CURRENT_USER\Software\Wine\X11 Driver\UseTakeFocus with value N
- Hotfix Confirmed
- Fixes game ignoring keyboard input as well
```

Which is confirmed on my setup -> Requesting new verb.

This issue is blocker to https://github.com/PhoenicisOrg/scripts/issues/934

**Comment by Kreyren** [comment]
Dunno if making verbs is the most effective way for small changes like this one btw.

**Comment by ImperatorS79** [comment]
A setting might more appropriate. You can do it yourself by looking at other wine settings in `Engines/Wine/Settings`
