### ISSUE TITLE
Add ModOrganizer 2

### ISSUE THREAD

**Issue by Kreyren** [PhoenicisOrg/scripts#955]
### BLOCKED BY https://bugs.winehq.org/show_bug.cgi?id=46697 (?)

---

Refferenced on :https://github.com/Nexus-Mods/Vortex/issues/93#issuecomment-497242865

> If MO2 VFS can be made to work via wine, then that be great but I have serious doubts...

i think @TanninOne told me what is beeing used, but i forgett >.>.. Can try to make it work on linux current issue tracker mensions NtQueryDirectoryFileEx conflict only https://bugs.winehq.org/show_bug.cgi?id=46697

---

![image](https://user-images.githubusercontent.com/11302521/58618145-2787fa80-82c2-11e9-8913-9b3d0c33417b.png)

Mod Organizer (MO) is a tool for managing mod collections of arbitrary size. It is specifically designed for people who like to experiment with mods and thus need an easy and reliable way to install and uninstall them.

### TESTS
Download from https://github.com/ModOrganizer2/modorganizer/releases

SRC_URI: https://github.com/ModOrganizer2/modorganizer/releases/download/v2.2.0/Mod.Organizer-2.2.0.0.exe

ModOrganizer 2 v2.2.0 used

Tested using `app-emulation/wine-staging-9999_p1:9999_p1::bobwya  USE="X alsa esync fontconfig jpeg mono mp3 opencl opengl osmesa png pulseaudio realtime run-exes samba sdl2 ssl threads truetype udev vkd3d vulkan xcomposite xml -capi -cups -custom-cflags -dos -faudio -ffmpeg -gecko -gphoto2 -gsm -gstreamer -kerberos -lcms -ldap -ncurses -netapi -nls -odbc -openal -oss -pba -pcap -perl -pipelight (-prefix) -prelink -s3tc -scanner (-selinux) -test -themes -udisks -v4l -vaapi -xinerama" ABI_X86="32 64 (-x32)`

`env WINEDEBUG="fixme-all" WINEPREFIX="${HOME}/Games/ModOrganizer" WINEARCH="win64" wine ${HOME}/Downloads/Mod.Organizer-2.2.0.0.exe`

`vcrun2017` mandatory

wineapp installs without errors

wineapp runs without errors atm, testing..

fetching winesteam with skyrim.

scaling was changed on 144dpi

using linux steam

runtime: 
![image](https://user-images.githubusercontent.com/11302521/58619813-f01b4d00-82c5-11e9-86f6-b045009a810a.png)

trying to install skyUI 

ERROR_01
![image](https://user-images.githubusercontent.com/11302521/58620039-6c159500-82c6-11e9-998d-c1353e50f487.png)

```
10:31:50 [D] Downloads after refresh: 1
10:31:53 [D] mod id guessed: SkyUI_5_1-3863-5-1.7z -> -1
10:31:53 [D] passed mod id: 0, guessed id: -1
10:31:53 [D] using mod name "SkyUI" (id 0) -> SkyUI_5_1-3863-5-1.7z
10:31:53 [D] Opened  "C:/users/kreyren/Local Settings/Application Data/ModOrganizer/Skyrim/downloads/SkyUI_5_1-3863-5-1.7z"  using  "7z"  (from signature)
10:31:54 [D] running c:\Modding\MO2\NCC\NexusClientCLI.exe -g Skyrim -p "C:\users\kreyren\Local Settings\Application Data\ModOrganizer\Skyrim\profiles\Default" -gd "Z:\home\kreyren\Steam\steamapps\common\Skyrim" -d "C:\users\kreyren\Local Settings\Application Data\ModOrganizer\Skyrim\overwrite"  -i "C:\users\kreyren\Local Settings\Application Data\ModOrganizer\Skyrim\downloads\SkyUI_5_1-3863-5-1.7z" "C:\users\kreyren\Local Settings\Application Data\ModOrganizer\Skyrim\mods\SkyUI"
10:31:57 [D] brought window to front
```

ended with errorcode 5

ERROR_02
![image](https://user-images.githubusercontent.com/11302521/58620121-9b2c0680-82c6-11e9-8d55-9ee11ca83efd.png)

Assuming affected by https://bugs.winehq.org/show_bug.cgi?id=46697

`NtQueryDirectoryFileEx` is not searchable in wine-staing, wine-patched nor wine-mirror on github

### WINEBUGS
`NtQueryDirectoryFileEx` - https://bugs.winehq.org/show_bug.cgi?id=46697

### REFERENCES
nexusmods.com page - https://www.nexusmods.com/skyrimspecialedition/mods/6194?tab=description

github - https://github.com/ModOrganizer2/modorganizer

**Comment by Kreyren** [comment]
RESERVED

**Comment by plata** [comment]
Please clean up the issue description to contain only the relevant information:
- which app is requested
- hints required to make it run (if any)

The current format does not allow anybody to work on this.

**Comment by Kreyren** [comment]
@plata based on available informations it's impossible to make it work on linux due missing implementation of `NtQueryDirectoryFileEx` in WINE. -> Keeping this format with my test results only.

> which app is requested
please..
![image](https://user-images.githubusercontent.com/11302521/58901803-7c16e580-86c7-11e9-8306-9395cdb20ac2.png)

> hints required to make it run (if any)

test results.. what more you want o.o did you even read it

**Comment by plata** [comment]
> based on available informations it's impossible to make it work on linux due missing implementation of NtQueryDirectoryFileEx in WINE

If this is the case, please close the issue because there's nothing we can do about it.

**Comment by Kreyren** [comment]
@plata counter-productive, add HELP_WANTED and keep open

**Comment by plata** [comment]
Declined. It doesn't help if we track issues we will never be able to solve. Feel free to re-open the app wish if we can technically implement it.

**Comment by Kreyren** [comment]
fair enough
