### ISSUE TITLE
REQUEST: Sandbox winbind

### ISSUE THREAD

**Issue by Kreyren** [PhoenicisOrg/scripts#977]
Results in 
![image](https://user-images.githubusercontent.com/11302521/58996123-8070fa80-87bc-11e9-9b5a-46a489835f37.png)

Should be probably sandboxed

_Originally posted by @Kreyren in https://github.com/PhoenicisOrg/scripts/pull/965#issuecomment-499287903_

**Comment by ImperatorS79** [comment]
@qparis I think we can add winbind as a .deb dependency like freetype.

**Comment by plata** [comment]
This is not related to scripts is it?

**Comment by Kreyren** [comment]
> This is not related to scripts, is it?

very related since it's required for all uplay and steam scripts where it outputs an annoying message on installation asking to install this dep manually.

**Comment by plata** [comment]
winbind is now part of the .deb. Like @ImperatorS79 explained, we cannot add it to the runtime.
