### ISSUE TITLE
QA: Uplay installation pops under

### ISSUE THREAD

**Issue by Kreyren** [PhoenicisOrg/scripts#980]
While new uplay installation is started it pops the installer window under uplay launcher which is annoying, should be fixed.

**Comment by plata** [comment]
I don't see what we good possibly do about this.

Unrelated: Why do you use the prefix "QA" very often?

**Comment by Kreyren** [comment]
> I don't see what we good possibly do about this.

Anything? 
- forcing focus on the pop-under
- Do not maximalize the uplay launcher and handle the actions from phoenicis only
- Hide the launcher in this stage
etc.. etc..

> Unrelated: Why do you use the prefix "QA" very often?

QA == Quality Assurance -> issues that are verifying the quality of the code.

**Comment by qparis** [comment]
Whatch your langage @Kreyren, really.
