### ISSUE TITLE
QA: Use `WINEDEBUG="fixme-all"` on phoenicis terminal

### ISSUE THREAD

**Issue by Kreyren** [PhoenicisOrg/scripts#983]
Use `WINEDEBUG="fixme-all"` on phoenicis terminal -> fixme's are relevant only to developers excluding special scenarion -> Remove them from the log to make debugging more effective.

**Comment by ImperatorS79** [comment]
I cannot agree with this because when you open such a terminal it is generally for debugging purposes and fixme are relevant to debug. But you can use such an environment variable if you wish. This will just not be the default.

**Comment by Kreyren** [comment]
fixme's are generally not relevant to debug unless you are debugging wine function where we usually debug just workaround, registry changes and compatibility making it useless.

**Comment by plata** [comment]
@qparis how has this been handled in PoL 4?

**Comment by Kreyren** [comment]
> @qparis how has this been handled in PoL 4?

recommends configuration file for end-users/contributors to specify what is expected from phoenicis.

**Comment by qparis** [comment]
@plata On POLv4, we have a "run" button and a "debug" button. When you use "debug", by default, it unsets WINEDEBUG (initially set to "-all" by POL). In general, this is sufficient for debuging purpose. If required, we also have a setting to override the debug level

**Comment by qparis** [comment]
However, this feature does absolutely not belong to scripts. I suggest we move it to Phoenicis, or we recreate a more general one

**Comment by plata** [comment]
> However, this feature does absolutely not belong to scripts.

I'm not so sure about this part. If we want to be truly generic regarding engines, it must be done in scripts.

**Comment by qparis** [comment]
You are right

**Comment by plata** [comment]
Can you create a new issue which is more general and precise? Maybe something like: "Control Wine debug level when running shortcuts".

**Comment by qparis** [comment]
Did it. The description will follow

**Comment by plata** [comment]
Superseded by #993.
