### ISSUE TITLE
Replace corefonts with FOSS alternative

### ISSUE THREAD

**Issue by Kreyren** [PhoenicisOrg/scripts#986]
Refferending here: https://github.com/Winetricks/winetricks/pull/1090

**Comment by plata** [comment]
I don't see how this affects us.

**Comment by Kreyren** [comment]
> I don't see how this affects us.

Afaik corefonts are using non-FOSS libraries -> Recommending to replace them with FOSS alternative that is beeing considered in Winetricks atm.

Unless you are telling me that you don't care for FOSS software :thinking:

**Comment by ImperatorS79** [comment]
If you read the winetricks issue, it is not even working perfectly atm. So wait and see.

**Comment by plata** [comment]
Apart from that:
- apparently there is no legal issue
- Proton provides corefonts functionality already
- it does not make any difference for the user (if any we will have more problems because the proposed solution does not work properly)

**Comment by Kreyren** [comment]
> If you read the winetricks issue, it is not even working perfectly atm. So wait and see.

yes, but that doesn't mean that we can't experiment with it.. in theory we can use FOSS fonts that are simmilar to original and just rename them or make symlink to them..

> apparently there is no legal issue

Open software dah.. Literally none wants to use proprietary on linux

> Proton provides corefonts functionality already

Irelevant

> it does not make any difference for the user (if any we will have more problems because the proposed solution does not work properly)

it makes a significant difference if linux system is using FOSS or proprietary code.. 

@ImperatorS79 can you explain FOSS to those two macbookers?

**Comment by ImperatorS79** [comment]
@Kreyren you should stop being so mind closed, and watch your language a little bit. @plata is using linux AFAIK, and most linux users (like 99%) does not care about using some proprietary things (Nvidia drivers, fonts, mp3 decoder, ...)

If they managed to get something I will be pleased to add this option to corefonts for big "bearded" linuxian ^^.

**Comment by plata** [comment]
Actually, this should simply be implemented as a separate verb. So @Kreyren feel free to provide a PR if you are interested.

**Comment by Kreyren** [comment]
> you should stop being so mind closed

i'm always open-minded challenge me if you think that my knowledge is wrong and i will welcome it.

> and most linux users (like 99%)

Depending where do you ask on high-end distros there is nothing proprietary excluding nvidia at maximum (or fonts if you need them for gimp and stuff).. On noob distros it's pretty common.. 

>  I will be pleased to add this option to corefonts for big "bearded" linuxian ^^ 
> So @Kreyren feel free to provide a PR if you are interested.

My glorious beard is satisfied with your solution
![image](https://user-images.githubusercontent.com/11302521/59055808-58d16f00-885c-11e9-8f2a-08311a3c4ece.png)
