### ISSUE TITLE
I cannot see what was difficult/pita here.

### ISSUE THREAD

**Issue by Kreyren** [PhoenicisOrg/scripts#996]
I cannot see what was difficult/pita here.

_Originally posted by @plata in https://github.com/PhoenicisOrg/scripts/pull/990#issuecomment-499929108_

> I cannot see what was difficult/pita here.

To update anything i have clone repository, make a new branch find corresponding file, edit it, make sure it pasts QA checks and then wait for you to approve it -> huge pita for documentation.

At least add the `edit` button on the phoenicis docs page that opens a github browser editor to corresponding file to make merge faster.

**Comment by qparis** [comment]
This github organization is not a forum. You cannot open an issue just because you want to continue a discussion. Please use title and description that are factual and self-explanatory.

**Comment by Kreyren** [comment]
@qparis it didn't save the title for some reason
